### ISSUE TITLE
Logo Design Proposal

### ISSUE THREAD

**Issue by debpedrano** [stevesoltys/backup#10]
Greetings!

Hello Project Owner, I am a designer and I am making logo, whats good now is I am offering you a free logo. Is there any chance I can contribute on your project?

**Comment by stevesoltys** [comment]
Sure, that would be great! Feel free to mock something up, preferably a launcher icon, and I'll let you know what I think.

**Comment by debpedrano** [comment]
These are some of my ideas about the logo, I made it simpler, B for Backup.

![image](https://user-images.githubusercontent.com/40510200/49696573-85c30300-fbe6-11e8-8a7b-943ac6add9f8.png)

**Comment by stevesoltys** [comment]
Nice job @debpedrano! I was thinking something more along the lines of this:

![](https://i.imgur.com/gIIRPw7.png)

It doesn't have to be that exact design but I think the icon should show the user that the application is meant for backing up data.

**Comment by debpedrano** [comment]
@stevesoltys i think User can already identify the logo that is backing up or in reverse. I can make some adjustment on it.

**Comment by stevesoltys** [comment]
Looks good to me @debpedrano, thanks!

Would you be able to open a pull request for this? Just need to replace `ic_launcher.png` in the different mipmap folders here: https://github.com/stevesoltys/backup/tree/master/app/src/main/res

**Comment by debpedrano** [comment]
Okay, ill make it..

**Comment by debpedrano** [comment]
Making this as your ReadMe Banner
![image](https://user-images.githubusercontent.com/40510200/49801892-6e228080-fd86-11e8-817b-7a0cba5ec5ff.png)

**Comment by stevesoltys** [comment]
I've just updated the launcher icon to be a bit different - but thank you anyways for this.

You're still welcome to design a README banner if you want. Here's the icon this app is using now: https://github.com/stevesoltys/backup/blob/09c8aad2373c9215ec4ed5959b8e7dac40c8efce/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png

**Comment by debpedrano** [comment]
I can enhance the color or maybe change the design a little bit if you wanted me to do so.

**Comment by stevesoltys** [comment]
I think the current launcher icon is good for now. Thanks for the help.
