### ISSUE TITLE
Adapt to Android 12 AOSP changes enhancement 

### ISSUE THREAD

**Issue by grote** [stevesoltys/backup#328]
AOSP 12 is out and we need to port Seedvault to it.

**Comment by grote** [comment]
storage: [can't start foreground services while running in the background](https://developer.android.com/about/versions/12/behavior-changes-12#foreground-service-launch-restrictions)

**Comment by chirayudesai** [comment]
> storage: [can't start foreground services while running in the background](https://developer.android.com/about/versions/12/behavior-changes-12#foreground-service-launch-restrictions)

"The user turns off battery optimizations for your app." is listed as an exception, so we can just get that.

**Comment by chris42** [comment]
Not sure if this is relevant or if others had the issue as well. I was just updating to android 12: 
- seedvault did a backup when I was connecting it via USB to save my files right before the update, so it was active
- Did the update via sideload
- Going into settings after the update and seedvault backup was turned off
- Could reactivate it by entering my passphrase

Not a big issue and not sure if this happened to others, but thought I mention it here.

**Comment by grote** [comment]
For old installations, having to re-set your passphrase when migrating to 12 is actually the expected behavior. The bit about having a backup running while upgrading not so much.

**Comment by chris42** [comment]
FYI: The backup finished before I did the upgrade. So then it behaved as expected.
