### ISSUE TITLE
The keyboard in vault doesn't go to password mode

### ISSUE THREAD

**Issue by ghost** [stevesoltys/backup#334]
![80d774a5-54c7-4b02-9924-1cef2f500273](https://user-images.githubusercontent.com/93206914/138900687-cb822b05-928d-4ebb-9e50-8287898c50a5.jpg)

When going to word list screen , the keyboard still gives suggestions as password in top of keyboard.
I'm using Gboard as my keyboard.

It would be nicer to not see any word suggestions from my keyboard.

![e7caccee-e3ec-49e8-a1cb-647a36c01a08](https://user-images.githubusercontent.com/93206914/138901167-30a13977-d300-420c-bc61-1aa707354260.jpg)

**Comment by grote** [comment]
You might find it nicer to not see suggestions. It is not clear to me why. I find the suggestions very helpful.

**Comment by ghost** [comment]
> You might find it nicer to not see suggestions. It is not clear to me why. I find the suggestions very helpful.

I'm talking about the horizontal suggestion bar above my keyboard not the vertical one that is in the app and only has the possible words from word list

**Comment by grote** [comment]
You might be missing this change in your version: https://github.com/seedvault-app/seedvault/pull/315

**Comment by chirayudesai** [comment]
> You might be missing this change in your version: #315

I believe they have that, it's 11-2.3

Maybe it's the `autoComplete` part?

**Comment by ghost** [comment]
Yes it's version 11-2.3 and suggestions are marked in the keyboard setting

**Comment by grote** [comment]
So the suggestions in the dropdown list should appear in the horizontal suggestion list of the keyboard?

Oh just see that the reporter user account was deleted.
