### ISSUE TITLE
Can not back up Android Media folder

### ISSUE THREAD

**Issue by DeveloperOl** [stevesoltys/backup#342]
Hi,

I was recently trying to include the folder "Android/Media/com.whatsapp/" in my seed vault backups. The folder is quite large and has ~15Gb with images, videos and databases.
But since I included this folder the backup fails. Removing the folder makes the backup work again but is not a considerable solution for me.

Is there any reason or known issues why this doesn't work?

**Comment by chirayudesai** [comment]
Would you be able to grab a logcat so that we can see why it's failing.

I do backup the same folder, however here it's only ~6Gb

**Comment by DeveloperOl** [comment]
@chirayudesai Thanks for the reply. I did some more debugging and it somehow started working when I disabled the "app backup". The app backup fails with a message similar to #335 so I will close this issue.
