### ISSUE TITLE
Can't restore data backed up by SeedVault

### ISSUE THREAD

**Issue by jvarghe** [stevesoltys/backup#344]
Previous OS: CalyxOS 2.11 (2021 November Release)
Current OS: CalyxOS 2.11 (2021 November Release)
Device: Google Pixel 3A

I had some personal data on my phone that I backed up with SeedVault before wiping and installing a fresh copy of CalyxOS. I have the restore code and backup files on my PC. 

I skipped the restoration offer during the setup process (It was a fresh installation. I hadn't transferred my backup data to the phone yet. It was kind of a stupid place to put the data restoration offer). 

As others have complained, SeedVault doesn't offer you an option to restore backups after that point!

I moved my backed up data into my phone's default local backup location: /.SeedVaultAndroidBackup

I googled and found the *#*#RESTORE#*#* dialer code thing, but SeedVault is giving me this error: "No suitable backups found at given location. This is most likely due to a wrong recovery code or a storage error." I am presented with no backups to restore and can only choose `Skip restoring apps`. I don't know what to do now.

I suspect I got this error because SeedVault forced me to select a new 12-word pass code after wiping, which does not match the pass code I was issued from BEFORE the wipe. So now, I have backup files encrypted via a pass phrase that the app's restoration process cannot even ask me for!? 

I understand a little bit about software development and I'm sympathetic to developers. But this is the incompetent thing I've seen in some time! Does nobody dogfood SeedVault? Its not a music player app, it's a data backup app! If there's one thing you need to respect, its the integrity of people's data! Did absolutely nobody try the restoration function of a data backup and restoration app?!? Why do I need to use the phone dialer to restore data? If one thing is clear, SeedVault is far too immature and buggy to have been released. It's in beta state at best. I'm not even an amateur programmer and I can tell you that this completely amateurish. 

Sorry for venting, but that needed to be said. To the developers: please re-think your entire development process. Identify the standard backup and restoration process and ensure these codepaths are rock solid before releasing them. At no point should data integrity be at risk. That should be a core value of people who develop a data backup and restoration app. 

Now, can someone please tell me to how to get SeedVault to recognize my backed up files, de-crypt them and restore them on to my phone, please?

**Comment by grote** [comment]
Ok you have convinced me. I'll quite computers and do something with wood instead! :wave: :axe:  :wood:

**Comment by chirayudesai** [comment]
> I skipped the restoration offer during the setup process (It was a fresh installation. I hadn't transferred my backup data to the phone yet. It was kind of a stupid place to put the data restoration offer).
> 

Restoring the phone before the setup is the expected flow. It's also how it works on stock, and trying to restore after setup just doesn't work as well.

> As others have complained, SeedVault doesn't offer you an option to restore backups after that point!
> 

See above.

> I moved my backed up data into my phone's default local backup location: /.SeedVaultAndroidBackup
> 

Internal storage should not be used for any important backup, we have a warning for that specifically to avoid having to run into these situations.

> I googled and found the _#_#RESTORE#_#_ dialer code thing, but SeedVault is giving me this error: "No suitable backups found at given location. This is most likely due to a wrong recovery code or a storage error." I am presented with no backups to restore and can only choose `Skip restoring apps`. I don't know what to do now.

Did the file copy go correctly? Do you know folder structure maintained?

> 
> I suspect I got this error because SeedVault forced me to select a new 12-word pass code after wiping, which does not match the pass code I was issued from BEFORE the wipe. So now, I have backup files encrypted via a pass phrase that the app's restoration process cannot even ask me for!?

Actually, it should've still worked. And the whole point of restoring before any setup is also avoid any edge cases like these.

> 
> I understand a little bit about software development and I'm sympathetic to developers. But this is the incompetent thing I've seen in some time! Does nobody dogfood SeedVault? Its not a music player app, it's a data backup app! If there's one thing you need to respect, its the integrity of people's data! Did absolutely nobody try the restoration function of a data backup and restoration app?!? Why do I need to use the phone dialer to restore data? If one thing is clear, SeedVault is far too immature and buggy to have been released. It's in beta state at best. I'm not even an amateur programmer and I can tell you that this completely amateurish.
> 

That's a bit harsh, don't you think?
1. You ignored warnings about backing up to internal storage
2. You didn't restore in the expected manner, which is during setup.

I can assure you that the restoration function definitely works. Not to say that it's perfect, there definitely are hiccups, but usually it does work.

> Sorry for venting, but that needed to be said. To the developers: please re-think your entire development process. Identify the standard backup and restoration process and ensure these codepaths are rock solid before releasing them. At no point should data integrity be at risk. That should be a core value of people who develop a data backup and restoration app.
> 
> Now, can someone please tell me to how to get SeedVault to recognize my backed up files, de-crypt them and restore them on to my phone, please?

I'd say best way would be to transfer the backup to a usb drive, make sure it's in the root, then try to setup the phone again and restore.

**Comment by jvarghe** [comment]
I'm sorry if I was a bit harsh yesterday. I don't want to be one of those entitled people who don't commit anything to a project but show up and criticize a lot. 

>>I skipped the restoration offer during the setup process (It was a fresh installation. I hadn't transferred my backup data to the phone yet. It was kind of a stupid place to put the data restoration offer).
>
>Restoring the phone before the setup is the expected flow. It's also how it works on stock, and trying to restore after setup just doesn't work as well.

I don't understand what you mean. I will explain my workflow. Intending to flash CalyxOS again, I backed up data with SeedVault. I made a copy of it on my PC. Then, I flashed CalyxOS again on my phone, which should have wiped out all existing data on my phone, including the backups. 

When my phone reboots after flashing, this is first time CalyxOS is running. So, it opens up the first boot setup process. Connecting to Wifi, choosing a PIN, enabling microG etc. This is also the time when CalyxOS presents me with the a SeedVault option to restore from backup.

But how am I supposed to restore backups at this point? All my existing backups got destroyed when I wiped the phone and installed CalyxOS anew. The SeedVault restore option shows up during the setup process, before I've even seen my homescreen yet. Before I can move backed up data to the phone, I need to fiddle with settings: enabling Developer Options, USB debugging, and USB file transfer. Only after than point can I even move files on the phone. 

Unless you are suggesting that somehow SeedVault has read permissions on my PC and should pull backup data from there? 

Even if this were the case, you understand that a backup solution that can only do restores once, during the setup phase, is not a very useful tool? I might need to restore some data off another phone at a later time; are you telling me that SeedVault is too limited for such an obvious use case? 


>Internal storage should not be used for any important backup, we have a warning for that specifically to avoid having to run into these situations.
>Did the file copy go correctly? Do you know folder structure maintained?

I don't really trust cloud backups, and an app that cannot reliably facilitate local backups is, again, quite useless. 

And I believe that the file transfer did go correctly. I would have checked the obvious failures.


>That's a bit harsh, don't you think?
>
>1. You ignored warnings about backing up to internal storage
>2. You didn't restore in the expected manner, which is during setup.

Your documentation is definitely lacking. Unless I've missed it, you have only an FAQ. And that consists of only three questions. 

I'll tell you what I'm looking for in a backup app. While cloud backups are useful, IMO a backup/restore app must get local backups right. FOSS enthusiasts are not really the sort to trust their data on a cloud somewhere. Otherwise, why do I need SeedVault? I would just use stock Android and use Google to save my backups. The entire point of using a custom ROM and a FOSS backup tool is to keep my data as far away from the cloud as possible. 

As to restoring during setup, I'm baffled by the suggestion. I don't know how you'd do it, unless the cloud is involved. Once again, I wonder how you guys overlooked the simplest and most secure way of saving data and moving it around: local backups. 


I just downloaded and tried OAndBackupX. It does require root, but it's much more full featured and more inline with what I expected from a backup app. May I ask, is SeedVault so limited because it doesn't require root permissions? Because it is missing basic functionality like local backups and prioritizes cloud backup instead. Is this a deliberate choice or the result of limitations imposed by a lack of root?

**Comment by nickcalyx** [comment]
"Does nobody dogfood SeedVault?"

"Because it is missing basic functionality like local backups"

I just switched phones the other day using SeedVault, with my local backups written to and then read from a usb-C memory stick.. that's the typical workflow for local backups, to use a memory stick that you can insert during the set up wizard.

If you want to help us make better documentation that would be very welcome

**Comment by ASerbinski** [comment]
For reference, the solution to the "restore after setup" problem is that you need to clear the application data for Seedvault, and then launch restore through the dialer code or adb (as root).

System Settings --> Apps --> See all --> Menu/Show System --> Seedvault --> Storage --> Clear Storage.
Dialer --> *#*#RESTORE#*#*

Now you can pick the storage location, enter the applicable secret words, and begin restoration.


IMO, the correct implementation for this would be not to railroad the user into setting up a new storage location when they first load Seedvault, but prompt them to restore or setup on first launch right after choosing the location, or maybe only prompt to restore if a backup is detected at that location.

**Comment by davidwitk** [comment]
I can confirm that Seedvault worked for me like a charm with a local backup. Used it yesterday for the first time to backup GrapheneOS, with the backup written to a USB stick and recovery during the set up wizard. Thanks for all your effort!

**Comment by Rahoon-GOAWAY** [comment]
@jvarghe, I had a similar issue and found a [workaround](https://github.com/seedvault-app/seedvault/issues/85#issuecomment-1063899414).

Doesn't fix the main issue but if you're still trying to restore that data you could try it.
