### ISSUE TITLE
Backing up of large files may cause backups to USB to become corrupt

### ISSUE THREAD

**Issue by Peter-Easton** [stevesoltys/backup#345]
Ahoy!

I thought I'd give you guys a shout, greatly appreciate the functionality that SeedVault has to offer! I believe I have discovered a bug, and I think I have figured out how to reproduce it. I unfortunately don't have screenshots (I didn't think to take them, d'oh!), but I thought I could describe it as closely as I could. I tried to test three different cases to attempt to narrow down the cause of the bug and I think I got them. 

I will try my best to record down my steps and I'll attach the report below. 

# Report

## Brief description
When backing up to a USB drive, files larger than 4GB may cause the backup to fail if selected for backup.

## Versions believed to be affected
Version: 11-2.3

## Equipment
* Google Pixel 3, running GrapheneOS (official unmodified release) 
* Google Pixel 4, running GrapheneOS (official unmodified release)
* Google Pixel 6 Pro, running GrapheneOS (official unmodified release)
* USB-C to USB-A adapter, included in box
* Corsair Voyager GTX USB Solid State Drive, 128GB, referred to in this report as "The USB SSD"
* Desktop Computer (details unimportant)
* Writing Implements

## Initial setup
Prior to use, the Corsair Voyager GTX USB SSD was first wiped with the use of an ordinary desktop computer. The USB SSD was then inserted into the Pixel 3, which was then allowed to format the drive using the default options. The recovery seed was recorded, backup was then run and tested successfully across two different devices, including transferring of the backup from a Pixel 3 to another Pixel 3, then from a Pixel 3 to a Pixel 4. At the time, SeedVault did not permit for file backup. The backup completed successfully and the same seed would then be reused for subsequent backups.

The backup would then be updated on the Pixel 4 with the test cases following below, and then restored to a Pixel 6 Pro.

### Case 1: Seedvault backup with a large file
The USB SSD was then placed into the desktop computer again and wiped before being connected to the Pixel 4, and the following options selected:

* Backup Location: Corsair USB Drive
* Backup My Apps: Yes
* Automatic Restore: Yes
* App Backup: Yes
* Backup My Files: Yes
* Files Selected For Backup: Pictures, Videos, Signal Backups.
* Unlimited App Quota (Expert): No

Numerous pictures and videos were to be included among the backup. None of the pictures or videos on disk had a size on disk exceeding 1GB. However, the Signal Backup directory contained two files of encrypted and uncompressible data which were both approximately 6GB in size. 

#### Expected Outcome
* SeedVault would display progress as it backed up files and apps.
* Once completed, Seedvault would report the backup as having been successful and allow its notifications to be dismissed.
* The backup would allow the files and apps to be restored on the new device.
* Apps that did not permit backup would not have their application data backed up, and would not have their application data restored.

#### Observed Outcome
After starting the backup, SeedVault indicated the following:

* Backup of Storage had failed, via a notification.
* Backup of apps was in progress

The notification that backing up of files had failed was displayed immediately, without reporting any progress. The notification indicating that the backup was in progress slowly completed as expected, before ending with the bar at 100%, upon which it remained in the notifications area and could not be dismissed or hidden without rebooting the device. When examining the status of the backup, SeedVault indicated that the backup had been taken successfully for the apps that allowed their data to be backed up as expected. 

A Pixel 6 Pro was prepared, then factory reset was selected. During the first-on initial Setup Wizard, the launcher prompted for the backup files. The USB SSD was connected to the phone and the Seed entered as recorded. Care was taken to ensure that the Seed phrase was entered correctly. The device reported that the Seed was invalid, or the backup could not be restored. After exiting the launcher, Restore (Experimental) was requested from the SeedVault menu, however, the screen persisted and could not be dismissed. 

To confirm the results, the Pixel 6 pro was factory reset a second time, and the results duplicated to ensure a mistyped word phrase had not thrown off results. The second attempt produced no deviation from the first. 

In anticipation of the next test case, the Pixel 6 was then factory reset a third time and kept in a powered-off state prior to running Case 2.

### Case 2: Seedvault backup with no files
The USB SSD was then returned to the desktop computer and erased, then connected to the Pixel 4. This time, the following options were selected for backup:

* Backup Location: Corsair USB Drive
* Backup My Apps: Yes
* Automatic Restore: Yes
* App Backup: Yes
* Backup My Files: No
* Files Selected For Backup: N/A
* Unlimited App Quota (Expert): No

#### Expected Outcome
As in Case 1.

#### Observed Outcome
No deviation from expected results.

#### Conclusions
* Seedvault backups when taken without files are working as intended. 

### Case 3: Seedvault backups with only small files.
The USB SSD was then connected to the Pixel 4 and the following options were selected for backup:

* Backup Location: Corsair USB Drive
* Backup My Apps: Yes
* Automatic Restore: Yes
* App Backup: Yes
* Backup My Files: Yes
* Files Selected For Backup: Photos
* Unlimited App Quota (Expert): No

#### Expected Outcome
As in Case 1.

#### Observed Outcome
No deviation from expected results. Seedvault reported that storage was being backed up. Upon completion, the notification went away on its own and was replaced with the "Backup Running" notification, which went to completion and reported the backup was successful. 

Due to time constraints this backup was not tested for restorability.

### Observations
* The Signal Backup files cannot be copied from the device's shared storage partition to the USB drive, as they exceed the maximum allowable file size of FAT32. 
* The Android system was allowed to format the USB SSD. Android does not at this moment permit the use of ext4 or btrfs with USB SSDs, and formats them as FAT32 by default. 

### Conclusions
* Storage backup to a USB drive may be hampered by the presence of large files which may not be able to be backed up onto detachable media. 
* Seedvault reports that the app backups have been taken successfully even if the backup has failed and is unreadable.
* The notification stalling at 100%, then the absence of it being reported as a success may be an indicator that the backup has failed. When combined with the indication that backing up of files has failed, this may hint to the user that their backup may not have been taken successfully.
* Backups taken in this state may be corrupted. Corrupted backups cannot be restored.
* Attempting to restore a corrupt backup results in SeedVault suffering a serious error, requiring a factory reset of the device to restore functionality to SeedVault.

## Closing thoughts
No data was lost during these tests.

**Comment by Peter-Easton** [comment]
I should clarify! 

Under the third conclusion, when I say "this may hint to the user that their backup may not have been taken successfully" I mean that as a **good** thing. Because it hung and didn't exit gracefully, I got the impression that the backup may have hung on exiting, and whenever cryptographic operations don't complete successfully usually that doesn't mean it fully worked. I'm actually very glad that it hung there and didn't exit cleanly, since that -- and the disclaimer that storage backup is experimental -- alerted me to have a backup taken via other means, just in case.

I'm actually very glad that it errored out and alerted me to the fact that the backups weren't complete. If it hadn't errored out, and I went through with it thinking my data was backed up, I could have ended up losing data.

**Comment by grote** [comment]
Thanks for the detailed bug report! If the error is reproducible, would you mind providing a logcat for the part where unexpected behavior happens?

**Comment by Peter-Easton** [comment]
Ahoy @grote ! Yessir, I'm working on that right now. I just had a few difficulties with another issue, I'll try to find it!

**Comment by grote** [comment]
I am closing this now, but please re-open once you manage to get logs or a way to reproduce the issue.
