### ISSUE TITLE
[Bug] `Keystore2:error in Import_Key` causes setup of SeedVault to loop infinitely.

### ISSUE THREAD

**Issue by Peter-Easton** [stevesoltys/backup#346]
Hello again,

While I was attempting to investigate https://github.com/seedvault-app/seedvault/issues/345 with a clean start and capture logcat, I think I found another bug. I'll try to see if I can document it here as best I can.

# Report

## Brief Description 
When setting up Seedvault, a bug in the setup process causes the setup process of Seedvault (Recording, then verifying the 12-word recovery seed) to repeat infinitely.

### Consequences
Seedvault is unable to be started.

### Version believed to be affected
Version: 11-2.3

## Equipment
* Desktop computer running Android Debug Bridge
* Google Pixel 4 (Flame) running GrapheneOS (Unmodified Official Release) 
* USB-C to USB-C cable (Official Google branded cable)
* Wireless Router
* USB-C male to USB-A female adapter (Official Google branded adapter)
* 32GB Kingston Data Traveller USB Drive 

### Preparation for investigating the previous bug
To prepare to investigate https://github.com/seedvault-app/seedvault/issues/345 , the Pixel 4 was first factory reset to give a clean image and ensure no confidential or private information would remain on the device. The USB drive was then inserted into the desktop computer and wiped, in anticipation that it would be connected to the phone and the phone permitted to format it during the test.

During the initial setup, the cellphone was connected to the wireless network, secured by means of a password. After proceeding through the remaining setup options, discarding security options (no pin code set, no data restored from seedvault), Developer Options were accessed, and the following options set:

* USB Debugging, set to ON
* WiFi Debugging, set to ON

Wireless Debugging was then enabled for the SSID the phone was connected to with the "Always" box checked. The desktop computer was then connected to the phone, Android Debug Bridge server started, and the computer's SSH key fingerprint set to "Always Trusted."

The following commands were run to attempt to recreate conditions similar to the test case in https://github.com/seedvault-app/seedvault/issues/345 and create a file between 5 and 6 Gigabytes of uncompressible data and simulate an encrypted Signal offline backup file.

```
adb shell 
flame:/ $ cd /sdcard
flame:/ $ mkdir /sdcard/BigFiles
flame:/ $ cd /sdcard/BigFiles
flame:/ $ dd if=/dev/urandom of=Junkfile.junk bs=4096 count=1464844
flame:/ $ exit
```

Finally, several high-resolution wallpapers in sizes averaging between 200KB and 1500KB were copied to the `Pictures` directory using MTP.

Dummy apps were to be installed for a subsequent test case, but the test did not progress this far. No other apps, configurations, or settings were changed.

### Connecting to Android Debug Bridge

The ADB Server was started on TCP Port 5555. The phone was plugged into the computer by via USB-C-to-USB-C cable, connected to WiFi Debugging, and the USB-C-to-C cable disconnected.

ADB Logcat was started and output piped to a file. 

## Setting up Seedvault

After initial setup had been completed, the USB drive was connected via the USB-C adapter. Seedvault was opened via the Settings Menu. At this stage, Seedvault provided 12 words for a seed phrase. As no confidential data was to be used during the test, the seed phrase was recorded temporarily onto the desktop computer, and the blue "Verify" button pressed, which prompted the same words to be entered back into the device to prove to the device that the seed phrase had been recorded accurately. 

To ensure robustness of the test, the word was entered, then when the correct entry appeared in the drop down list, the entry in the drop-down list was selected to ensure accuracy. At one point, the "confirm" button was pressed when not all the words had been entered, to confirm that Seedvault would detect the error and prompt for user correction.

### Expected Outcome
Seedvault would accept the seed phrase, then proceed to the backup menu to allow backups to be taken. In the event of a missing word, Seedvault would prompt for the missing word.

### Observed Outcome 
After pressing the button to confirm that all twelve words had been entered accordingly, Seedvault immediately started back at where it began with a new seed phrase. After recording, then confirming the new seed phrase, Seedvault returned to the System settings menu. 

When the backup menu was selected again, the same would result: a new seed phrase would be displayed to the user. When the seed phrase was recorded, then reentered on the phone, the process would repeat with a new seed phrase. When the new seed phrase was subsequently recorded and reentered, Seedvault would return the user to the System settings menu. 

As expected, when a word was deliberately omitted from the word list, Seedvault prompted for the missing word.

The logs were collected and are attached to the bottom of this report

## Preliminary conclusions
This bug blocks Seedvault from being initialized for the first time. 

# ADB Log 
The full logs have been sent in for analysis, but this looks promising!

```
12-16 08:56:51.526   617   631 D DrmLibTime: QSEE Time Listener: Time GenOff - seconds: 1639684613
12-16 08:56:51.526   617   631 D DrmLibTime: time_getutcsec returns 0, sec = 1639684613; nsec = 0
12-16 08:56:51.526   617   631 D DrmLibTime: time_getutcsec finished! 
12-16 08:56:51.526   617   631 D DrmLibTime: iotcl_continue_command finished! and return 0 
12-16 08:56:51.526   617   631 D DrmLibTime: before calling ioctl to read the next time_cmd
12-16 08:56:51.529   802   977 E QC-time-services: Daemon: Time-services: Waiting to acceptconnection
12-16 08:56:51.534   697   697 E keystore2: keystore2::error: In import_key.
12-16 08:56:51.534   697   697 E keystore2: 
12-16 08:56:51.534   697   697 E keystore2: Caused by:
12-16 08:56:51.534   697   697 E keystore2:     0: In store_new_key.
12-16 08:56:51.534   697   697 E keystore2:     1: In store_new_key. Failed to handle super encryption.
12-16 08:56:51.534   697   697 E keystore2:     2: In handle_super_encryption_on_key_init: User ECDH key missing.
12-16 08:56:51.534   697   697 E keystore2:     3: Error::Rc(ResponseCode(4))
12-16 08:56:51.535  7846  7846 D AndroidRuntime: Shutting down VM
12-16 08:56:51.535  7846  7846 E AndroidRuntime: FATAL EXCEPTION: main
12-16 08:56:51.535  7846  7846 E AndroidRuntime: Process: com.stevesoltys.seedvault, PID: 7846
12-16 08:56:51.535  7846  7846 E AndroidRuntime: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
12-16 08:56:51.535  7846  7846 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:558)
12-16 08:56:51.535  7846  7846 E AndroidRuntime: 	at com.android.internal.os.ExecInit.main(ExecInit.java:48)
12-16 08:56:51.535  7846  7846 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
12-16 08:56:51.535  7846  7846 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
12-16 08:56:51.535  7846  7846 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
12-16 08:56:51.535  7846  7846 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-16 08:56:51.535  7846  7846 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
12-16 08:56:51.535  7846  7846 E AndroidRuntime: 	... 3 more
12-16 08:56:51.535  7846  7846 E AndroidRuntime: Caused by: java.security.KeyStoreException: Failed to import secret key.
12-16 08:56:51.535  7846  7846 E AndroidRuntime: 	at android.security.keystore2.AndroidKeyStoreSpi.setSecretKeyEntry(AndroidKeyStoreSpi.java:806)
12-16 08:56:51.535  7846  7846 E AndroidRuntime: 	at android.security.keystore2.AndroidKeyStoreSpi.engineSetEntry(AndroidKeyStoreSpi.java:1176)
12-16 08:56:51.535  7846  7846 E AndroidRuntime: 	at java.security.KeyStore.setEntry(KeyStore.java:1596)
12-16 08:56:51.535  7846  7846 E AndroidRuntime: 	at com.stevesoltys.seedvault.crypto.KeyManagerImpl.storeBackupKey(KeyManager.kt:73)
12-16 08:56:51.535  7846  7846 E AndroidRuntime: 	at com.stevesoltys.seedvault.ui.recoverycode.RecoveryCodeViewModel.storeNewCode(RecoveryCodeViewModel.kt:89)
12-16 08:56:51.535  7846  7846 E AndroidRuntime: 	at com.stevesoltys.seedvault.ui.recoverycode.RecoveryCodeInputFragment.done(RecoveryCodeInputFragment.kt:159)
12-16 08:56:51.535  7846  7846 E AndroidRuntime: 	at com.stevesoltys.seedvault.ui.recoverycode.RecoveryCodeInputFragment.access$done(RecoveryCodeInputFragment.kt:42)
12-16 08:56:51.535  7846  7846 E AndroidRuntime: 	at com.stevesoltys.seedvault.ui.recoverycode.RecoveryCodeInputFragment$onViewCreated$3.onClick(RecoveryCodeInputFragment.kt:125)
12-16 08:56:51.535  7846  7846 E AndroidRuntime: 	at android.view.View.performClick(View.java:7441)
12-16 08:56:51.535  7846  7846 E AndroidRuntime: 	at android.view.View.performClickInternal(View.java:7418)
12-16 08:56:51.535  7846  7846 E AndroidRuntime: 	at android.view.View.access$3700(View.java:835)
12-16 08:56:51.535  7846  7846 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:28677)
12-16 08:56:51.535  7846  7846 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
12-16 08:56:51.535  7846  7846 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
12-16 08:56:51.535  7846  7846 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
12-16 08:56:51.535  7846  7846 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
12-16 08:56:51.535  7846  7846 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7841)
12-16 08:56:51.535  7846  7846 E AndroidRuntime: 	... 5 more
12-16 08:56:51.535  7846  7846 E AndroidRuntime: Caused by: android.security.KeyStoreException: System error
12-16 08:56:51.535  7846  7846 E AndroidRuntime: 	at android.security.KeyStore2.getKeyStoreException(KeyStore2.java:334)
12-16 08:56:51.535  7846  7846 E AndroidRuntime: 	at android.security.KeyStoreSecurityLevel.handleExceptions(KeyStoreSecurityLevel.java:57)
12-16 08:56:51.535  7846  7846 E AndroidRuntime: 	at android.security.KeyStoreSecurityLevel.importKey(KeyStoreSecurityLevel.java:166)
12-16 08:56:51.535  7846  7846 E AndroidRuntime: 	at android.security.keystore2.AndroidKeyStoreSpi.setSecretKeyEntry(AndroidKeyStoreSpi.java:803)
12-16 08:56:51.535  7846  7846 E AndroidRuntime: 	... 21 more
12-16 08:56:51.536  7846  7846 E AndroidRuntime: Error reporting crash
12-16 08:56:51.536  7846  7846 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
12-16 08:56:51.536  7846  7846 E AndroidRuntime: 	at android.os.BinderProxy.transactNative(Native Method)
12-16 08:56:51.536  7846  7846 E AndroidRuntime: 	at android.os.BinderProxy.transact(BinderProxy.java:571)
12-16 08:56:51.536  7846  7846 E AndroidRuntime: 	at android.app.IActivityManager$Stub$Proxy.handleApplicationCrash(IActivityManager.java:5294)
12-16 08:56:51.536  7846  7846 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$KillApplicationHandler.uncaughtException(RuntimeInit.java:156)
12-16 08:56:51.536  7846  7846 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
12-16 08:56:51.536  7846  7846 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
12-16 08:56:51.536  7846  7846 E AndroidRuntime: 	at java.lang.Thread.dispatchUncaughtException(Thread.java:2200)
12-16 08:56:51.536  7846  7846 I Process : Sending signal. PID: 7846 SIG: 9
12-16 08:56:51.569   854   854 I Zygote  : Process 7846 exited due to signal 9 (Killed)
12-16 08:56:51.569  1624  7419 I ActivityManager: Process com.stevesoltys.seedvault (pid 7846) has died: fg  TOP 
12-16 08:56:51.569  1624  1700 I libprocessgroup: Successfully killed process cgroup uid 10025 pid 7846 in 0ms
12-16 08:56:51.569  1624  3729 I WindowManager: WIN DEATH: Window{1b80cf2 u0 com.stevesoltys.seedvault/com.stevesoltys.seedvault.ui.recoverycode.RecoveryCodeActivity}
12-16 08:56:51.569  1624  3729 W InputManager-JNI: Input channel object '1b80cf2 com.stevesoltys.seedvault/com.stevesoltys.seedvault.ui.recoverycode.RecoveryCodeActivity (client)' was disposed without first being removed with the input manager!
12-16 08:56:51.574  1624  7419 W ActivityTaskManager: Force removing ActivityRecord{18c91cb u0 com.stevesoltys.seedvault/.ui.recoverycode.RecoveryCodeActivity t18}: app died, no saved state
12-16 08:56:51.581   712   712 E BpTransactionCompletedListener: Failed to transact (-32)
12-16 08:56:51.585  1624  1688 W ActivityManager: setHasOverlayUi called on unknown pid: 7846
12-16 08:56:51.586  3948  3948 D DashboardFragment: register observer: @e4ba758, uri: content://com.android.settings.dashboard.SummaryProvider/user
12-16 08:56:51.589  3948  3948 D AssistGesture: mAssistOnly:false, isSupported:false, isSensorAvailable:false
12-16 08:56:51.589  1624  3729 I SystemUpdateManagerService: No existing info file /data/system/system-update-info.xml
12-16 08:56:51.589  3948  3948 D SysUpdatePrefContr: Update statue unknown
12-16 08:56:51.597  3948  7087 D SettingsActivity: No enabled state changed, skipping updateCategory call
```

**Comment by chirayudesai** [comment]
This bug is why we added the commit: https://github.com/seedvault-app/seedvault/commit/75d4c7d05cc7356c923c7eb830a64448e5aed1f6

It looks like it is reverted in your build, which is why you see that stacktrace.
