### ISSUE TITLE
Restore: Have to select "Don't restore" twice to actually exit since 12

### ISSUE THREAD

**Issue by chirayudesai** [stevesoltys/backup#352]
The restore activity, launched either via SetupWizard, `*#*#RESTORE#*#*`, allows you to select "Don't Restore" (or hit the back button / use android back gesture)

On 11: Don't Restore / back exits
On 12: Don't Restore / back brings the same activity again.

line 1  03:07:50.000 launched activity from SetupWizard
line 7 03:07:52.024 tapped don't restore first time
line 14 03:07:54.504 tapped it second time

Partial log (`logcat | grep seedvault`):
```
12-30 03:07:50.000  1854 10406 I ActivityTaskManager: START u0 {act=com.stevesoltys.seedvault.RESTORE_BACKUP cmp=com.stevesoltys.seedvault/.restore.RestoreActivity (has extras)} from uid 1000
12-30 03:07:50.030 21392 21392 E SetupLibrary: [PartnerCustomizationLayout] Attribute sucUsePartnerResource not found in ComponentInfo{com.stevesoltys.seedvault/com.stevesoltys.seedvault.restore.RestoreActivity}
12-30 03:07:50.044  1854 10406 I ActivityTaskManager: START u0 {cmp=com.stevesoltys.seedvault/.ui.storage.StorageActivity (has extras)} from uid 10124
12-30 03:07:50.070 21392 21392 E SetupLibrary: [PartnerCustomizationLayout] Attribute sucUsePartnerResource not found in ComponentInfo{com.stevesoltys.seedvault/com.stevesoltys.seedvault.ui.storage.StorageActivity}
12-30 03:07:50.115  1854  2229 I ActivityTaskManager: Displayed com.stevesoltys.seedvault/.ui.storage.StorageActivity: +112ms

12-30 03:07:52.024  1854  2854 I ActivityTaskManager: START u0 {cmp=com.stevesoltys.seedvault/.ui.storage.StorageActivity (has extras)} from uid 10124
12-30 03:07:52.035 21392 21392 W com.stevesoltys.seedvault.ui.RequireProvisioningActivity: Error in activity result for requesting location
12-30 03:07:52.062 21392 21392 E SetupLibrary: [PartnerCustomizationLayout] Attribute sucUsePartnerResource not found in ComponentInfo{com.stevesoltys.seedvault/com.stevesoltys.seedvault.ui.storage.StorageActivity}
12-30 03:07:52.104  1854  2229 I ActivityTaskManager: Displayed com.stevesoltys.seedvault/.ui.storage.StorageActivity: +80ms
12-30 03:07:52.175  1854 10406 W InputManager-JNI: Input channel object 'c76d187 com.stevesoltys.seedvault/com.stevesoltys.seedvault.restore.RestoreActivity (client)' was disposed without first being removed with the input manager!
12-30 03:07:52.644  1854 11069 W InputManager-JNI: Input channel object '7e9c9d9 com.stevesoltys.seedvault/com.stevesoltys.seedvault.ui.storage.StorageActivity (client)' was disposed without first being removed with the input manager!

12-30 03:07:54.504  1854  3195 W InputManager-JNI: Input channel object '67a4744 com.stevesoltys.seedvault/com.stevesoltys.seedvault.ui.storage.StorageActivity (client)' was disposed without first being removed with the input manager!
```

**Comment by grote** [comment]
The reason why I couldn't reproduce this before is that I was testing with seedvault set up, but this needs 

`adb shell pm clear com.stevesoltys.seedvault `

before reproducing.

**Comment by echeoquehaii** [comment]
Hi @grote!
I'm having this issue on LOS 19. I had SeedVault set up but with an old backup which I didn't need anymore, so I did

`adb shell pm clear com.stevesoltys.seedvault ` 

to start from scratch. Now I'm SeedVault is crashing when trying to start the backup process and in my logs I get the same as @chirayudesai. 

How can I correctly start a backup now? Can I use the fix in some way on my system?

**Comment by grote** [comment]
This ticket is not about crashing. If your seedvault is crashing, please open a new ticket with a qualified bug reports that includes all information necessary to diagnose this.

**Comment by echeoquehaii** [comment]
> This ticket is not about crashing. If your seedvault is crashing, please open a new ticket with a qualified bug reports that includes all information necessary to diagnose this.

Uh, sorry, will do now!
