### ISSUE TITLE
Backing up apps with no associated app-data

### ISSUE THREAD

**Issue by ChaosNicro** [stevesoltys/backup#355]
One timesink that setting up a new device has is redownloading apps. While f-droid and other sources allow you to export a list of installed Apps and many launchers can backup their layouts, you still have to go through the list and install what you want to keep.

Many Apps do not allow for system backups, do they still get restored without their data and if not could it be an option?

**Comment by grote** [comment]
This sounds more like [a question](https://github.com/seedvault-app/seedvault/discussions) than an actual issue, right?

The expected behavior is that Seedvault does back up APKs and re-installs them, even if the app doesn't allow data backup. Did you see an issue with that feature?
