### ISSUE TITLE
Confusing message (internal storage) when backing up to (external) SD card

### ISSUE THREAD

**Issue by davidmef** [stevesoltys/backup#360]
I am using version 11-2.3 from LineageOS to back up to the SD card. Currently the Spanish-language setting is set as "Ubicación de la copia de seguridad: Tarjeta SD Samsung (Almacenamiento interno)" that, in English, is probably "Backup location: SD Samsung card (Internal storage)".
The message made me doubt if I am backing up to my real SD card, that I can detach ("Almacenamiento portátil", i.e. "Portable storage", /storage/<hexadecimal code>), or to the simulated SD card ("Almacenamiento interno compartido", i.e., "Shared internal storage", /storage/emulated/0).
I checked and there is a .SeedVaultAndroidBackup in the real SD card, so it works.
I don't know if it is a problem of LineageOS or the Spanish translation. Could you make clearer in the message that the SD card is the "portable storage" or other similar label that is not "internal storage"?

Thanks for the application.

**Comment by grote** [comment]
the messages come from translations and the system itself. I personally don't have a test phone that takes SD cards.
