### ISSUE TITLE
Make clearer why the backup failed

### ISSUE THREAD

**Issue by davidmef** [stevesoltys/backup#361]
I tried to backup to my SD card. After a long time, the backup failed. Some of the applications had a yellow warning icon and at least one a red icon. I then found that the SD card was full, so of course it had failed, but I could not see clearly in Seedvault. Could you make visible the reason of the failure, at least, when it is because the destination is full, which I think is a frequent case?

**Comment by grote** [comment]
I am afraid that the internal AOSP backup API doesn't give us this information, but we could try to make some guesses, if that helps. Handling out of storage situations better should probably be a priority.

**Comment by grote** [comment]
we are now detecting and warning about out of space situations, if we can detect them.
