### ISSUE TITLE
Eleventh and twelfth restore word is not visible

### ISSUE THREAD

**Issue by a-riemer** [stevesoltys/backup#365]
See screen. Therefore a backup can not be initiated.

Edit (21:32): Words are visible if I reduce the system font size to minimum.

![Screenshot_20220111-210731_Seedvault](https://user-images.githubusercontent.com/17875015/149015314-0e20b04c-b9f1-47e0-8379-5f8208dcd1c8.png)

**Comment by grote** [comment]
This looks like a duplicate, probably on old version of Seedvault.

**Comment by a-riemer** [comment]
I used the version embedded in LineageOS 18.1.

**Comment by grote** [comment]
What version of Seedvault gets shown in the about dialog?
