### ISSUE TITLE
Don't treat 0-sized files as available

### ISSUE THREAD

**Issue by zroug** [stevesoltys/backup#369]
Seedvault should not depend on files that have size zero for new backups.

With remote backends that don't have a local cache it is very common to have write errors, but they can happen with other backends too (for example if Android crashes). The new file format makes it very important that Seedvault does not depend on corrupted files because they might be used for a long time, possibly forever.

Of course there can be write errors other than zero sized files but zero sized files are special because they are inherent to the storage access framework of Android and easy to detect. A good backend could implement atomic writes to avoid corrupted files but it cannot prevent zero sized files, because creating files and writing to them is always a two step process with the saf.

I'm not familiar with the source code of Seedvault but I think a very basic implementation would be as simple as ignoring zero sized files in [`getAvailableChunkIds`](https://github.com/seedvault-app/seedvault/blob/17a83eaab303c3dc98360cc5589fe2399f5e9f4d/storage/lib/src/main/java/org/calyxos/backup/storage/plugin/saf/SafStoragePlugin.kt#L66).

There can be other improvements too: Seedvault could delete zero sized files. Currently it also tries to prune zero sized `.SeedSnap` files again and again and does of course never succeed, that could be improved.

This change would fix backends that use atomic writes. For other backends there is more work to do but I think this would be a good starting point, because zero sized files can not be fixed by the storage provider.

**Comment by grote** [comment]
Can you please explain a bit clearer what the expected behavior is and what you are seeing instead?

**Comment by zroug** [comment]
Sorry for the late answer, I think I missed the notification. But after some more testing I realized that errors on the Android and SeedVault side can't always be detected by a document provider. That breaks the requirement for atomic updates. Therefore this issue is invalid actually.

I still think that incomplete uploads should get detected by subsequent runs of SeedVault, maybe by comparing the size of existing files to the expected size or something. But that would be a different issue.
