### ISSUE TITLE
Use root to backup unsupported apps and no_backup and cache of supported apps

### ISSUE THREAD

**Issue by upintheairsheep** [stevesoltys/backup#370]
For unsupported apps, backup the entire folder via root in another directory if you choose so. For supported apps, the cache, code cache, and no_backup are not backed up so put in the settings an option to back those folders up in another directory and restore them.

**Comment by grote** [comment]
This is not something seedvault can do as it doesn't get exposed via AOSP backup API AFAIK. Seedvault doesn't use root.
