### ISSUE TITLE
WebDAV backup fails - error creating root backup dir

### ISSUE THREAD

**Issue by metronidazole** [stevesoltys/backup#373]
I'm trying to use the new WebDAV backend however it keeps on failing with "a device backup failed to run". Looking at logcat shows the following:

> Error creating root backup dir.
> java.io.IOException
> 	at com.stevesoltys.seedvault.plugins.saf.DocumentsStorageKt.createOrGetDirectory(DocumentsStorage.kt:172)
> 	at com.stevesoltys.seedvault.plugins.saf.DocumentsStorageKt$createOrGetDirectory$1.invokeSuspend(Unknown Source:13)
> 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
> 	at kotlinx.coroutines.ResumeModeKt.resumeUninterceptedMode(ResumeMode.kt:45)
> 	at kotlinx.coroutines.TimeoutCoroutine.afterCompletionInternal(Timeout.kt:100)
> 	at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:310)
> 	at kotlinx.coroutines.JobSupport.tryFinalizeFinishingState(JobSupport.kt:236)
> 	at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:849)
> 	at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:811)
> 	at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:787)
> 	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:111)
> 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
> 	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
> 	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:270)
> 	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:79)
> 	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:54)
> 	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
> 	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:36)
> 	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
> 	at com.stevesoltys.seedvault.plugins.saf.DocumentsStorage.getRootBackupDir$packages__apps__Seedvault__android_common__Seedvault(DocumentsStorage.kt:56)
> 	at com.stevesoltys.seedvault.plugins.saf.DocumentsStorage$currentSetDir$1.invokeSuspend(DocumentsStorage.kt:85)
> 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
> 	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
> 	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:270)
> 	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:79)
> 	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:54)
> 	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
> 	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:36)
> 	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
> 	at com.stevesoltys.seedvault.plugins.saf.DocumentsStorage.getCurrentSetDir(DocumentsStorage.kt:81)
> 	at com.stevesoltys.seedvault.plugins.saf.DocumentsStorage.getSetDir(DocumentsStorage.kt:109)
> 	at com.stevesoltys.seedvault.plugins.saf.DocumentsStorage.getSetDir$default(DocumentsStorage.kt:108)
> 	at com.stevesoltys.seedvault.plugins.saf.DocumentsProviderStoragePlugin.initializeDevice(DocumentsProviderStoragePlugin.kt:37)
> 	at com.stevesoltys.seedvault.transport.backup.BackupCoordinator.initializeDevice(BackupCoordinator.kt:124)
> 	at com.stevesoltys.seedvault.transport.ConfigurableBackupTransport$initializeDevice$1.invokeSuspend(ConfigurableBackupTransport.kt:115)
> 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
> 	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
> 	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:270)
> 	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:79)
> 	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:54)
> 	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
> 	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:36)
> 	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
> 	at com.stevesoltys.seedvault.transport.ConfigurableBackupTransport.initializeDevice(ConfigurableBackupTransport.kt:114)
> 	at android.app.backup.BackupTransport$TransportImpl.initializeDevice(BackupTransport.java:698)

I think the issue is that my WebDAV server requires you to use a subfolder (full r/w) and not the root directory (read only). It would be nuce if you could make the webDAV root folder choosable in seedvault

**Comment by grote** [comment]
> I  think the issue is that my WebDAV server requires you to use a subfolder 

That sounds very likely and is thus not a Seedvault issue.

> It would be nuce if you could make the webDAV root folder choosable in seedvault

We don't allow custom folders to simplify the UX (where did I store my backups again... :thinking: ).

This is already tracked here: https://github.com/seedvault-app/seedvault/issues/143

**Comment by metronidazole** [comment]
Well that just makes seedvault even more useless. Fair enough. It's your app.
