### ISSUE TITLE
Restore via nextcloud fails when seedvault tries to restore nextcloud app

### ISSUE THREAD

**Issue by jejb** [stevesoltys/backup#374]
This is on Lineageos 17.1 without any gapps (so restore has to follow the procedure outlined in #251).  I get full restore of apps then seedvault begins restoring settings, but when it gets to restoring the settings of nextcloud, the nextcloud app crashes and can't be made to work again without a reboot.  Obviously this halts the restore process.  Logcat just shows a null pointer dereference in nextcloud, but I assume some change in its settings file caused this.

It looks like if seedvault wants to use an external app for backup and restore, it can't restore that app until everything else is finished.  This could also be fixed by implementing a separate webdav backend to seedvault so it could communicate with nextcloud without using an external app as suggested in #317.

**Comment by grote** [comment]
Seedvault should not restore Nextcloud when it is used for restoring as this kills the app. We have code to handle the backup, but didn't foresee people making a backup without Nextcloud and then restoring with Nextcloud.

**Comment by grote** [comment]
As a workaround, maybe you see which file it uses to store nextcloud data in logcat and delete that from backup.

**Comment by jejb** [comment]
On Mon, 2022-01-24 at 10:21 -0800, Torsten Grote wrote:
> Seedvault should not restore Nextcloud when it is used for restoring
> as this kills the app.

Right, that's the problem.

>  We have code to handle the backup, but didn't foresee people making
> a backup without Nextcloud and then restoring with Nextcloud.

To be clear: this backup was made with nextcloud and then restored with
nextcloud.  The only problem is because this is a non gapp phone the
restore can't be done from the first init wizard, it has to be done
from the dialer after nextcloud has been installed by f-droid.

James

**Comment by grote** [comment]
> this backup was made with nextcloud and then restored with nextcloud. 

Then there might be two bugs here. If you do another backup, can you confirm that nextcloud gets backed up while using nextcloud for backup (shouldn't actually work due to same app restart) and that there is only one nextcloud version installed?

**Comment by jejb** [comment]
On Wed, 2022-01-26 at 10:17 -0800, Torsten Grote wrote:
> Then there might be two bugs here. If you do another backup, can you
> confirm that nextcloud gets backed up while using nextcloud for
> backup (shouldn't actually work due to same app restart) and that
> there is only one nextcloud version installed?

Yes, I can confirm both.  (I've had the problem before with the
Nextcloud dev app vs the Nextcloud app so I'm careful to make sure
there's only one nextcloud file handler installed).  In the backup I
see the com.nextcloud.client.apk and then an encrypted entry under
full/com.nextcloud.client

I've actually tried to exclude the nextcloud client from the backup
using the exclude tab, but it still seems to be there.

James

**Comment by HerHde** [comment]
It seems like I have the same problem under LOS 19.

> but when it gets to restoring the settings of nextcloud, the nextcloud app [or seedvault, idk] crashes

**Comment by Th0masL** [comment]
I guess the easiest fix would be to disable the backup of nextcloud by default, and add something in the settings menu to eventually enable the backup of nextcloud for those who really want to backup the nextcloud app with seedvault.

**Comment by grote** [comment]
Should be fixed with https://github.com/seedvault-app/seedvault/pull/422
