### ISSUE TITLE
Whatsapp directory backed up?

### ISSUE THREAD

**Issue by anaxonda** [stevesoltys/backup#379]
On Android 11 (lineageOS). I recently did a system restore. Whatsapp data did not restore. I believe this data is stored at /Android/media/com.whatsapp.

Was I mistaken in thinking Seedvault should backup this data, or should I have been specifically backing up this directory?

Thanks

**Comment by grote** [comment]
AFAIK `/Android/media/com.whatsapp` is not accessible on Android 11. Also, it would require that you back up this manually with Seedvault files backup.  Also AFAIK WhatsApp doesn't use the android backup API, but has its own mechanism for backups.
