### ISSUE TITLE
installed successfully while failed to launch activity

### ISSUE THREAD

**Issue by beckietech** [stevesoltys/backup#380]
I'm new to this project and I successfully compiled storage app in my first trial; however, for seedvault app and contactsbackup app, the error message showed:
02/02 14:24:44: Launching 'app' on Google Pixel 2 XL.
Install successfully finished in 980 ms.
Could not identify launch activity: Default Activity not found
Error while Launching activity
Failed to launch an application on all devices

Can anyone let me know the error comes from this project or android studio itself? Thanks

**Comment by beckietech** [comment]
hi, I figure it out by looking this post:
https://community.e.foundation/t/howto-use-seedvault-early-to-understand-android-backup/34298
however, when I type :
adb shell am start-activity com.stevesoltys.seedvault/.settings.SettingsActivity

here is logcat info:
02-16 12:47:37.755   815  1457 E ActivityTaskManager: executeRequest: trafficIntent =null
02-16 12:47:38.908  5531  5531 E AndroidRuntime: FATAL EXCEPTION: main
02-16 12:47:38.908  5531  5531 E AndroidRuntime: Process: com.stevesoltys.seedvault, PID: 5531
02-16 12:47:38.908  5531  5531 E AndroidRuntime: java.lang.NoSuchMethodError: No static method getSupportedLocales(Landroid/content/Context;)[Ljava/lang/String; in class Lcom/android/internal/app/LocalePicker; or its super classes (declaration of 'com.android.internal.app.LocalePicker' appears in /system/framework/framework.jar!classes3.dex)
02-16 12:47:38.908  5531  5531 E AndroidRuntime:        at com.stevesoltys.seedvault.restore.install.DeviceInfo.<init>(DeviceInfo.kt:12)
02-16 12:47:38.908  5531  5531 E AndroidRuntime:        at com.stevesoltys.seedvault.restore.install.InstallModuleKt$installModule$1$2.invoke(InstallModule.kt:8)
02-16 12:47:38.908  5531  5531 E AndroidRuntime:        at com.stevesoltys.seedvault.restore.install.InstallModuleKt$installModule$1$2.invoke(Unknown Source:4)
02-16 12:47:38.908  5531  5531 E AndroidRuntime:        at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:53)
02-16 12:47:38.908  5531  5531 E AndroidRuntime:        at org.koin.core.instance.FactoryInstanceFactory.get(FactoryInstanceFactory.kt:38)
02-16 12:47:38.908  5531  5531 E AndroidRuntime:        at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:103)
02-16 12:47:38.908  5531  5531 E AndroidRuntime:        at org.koin.core.scope.Scope.resolveValue(Scope.kt:223)
02-16 12:47:38.908  5531  5531 E AndroidRuntime:        at org.koin.core.scope.Scope.resolveInstance(Scope.kt:211)
02-16 12:47:38.908  5531  5531 E AndroidRuntime:        at org.koin.core.scope.Scope.get(Scope.kt:193)
02-16 12:47:38.908  5531  5531 E AndroidRuntime:        at com.stevesoltys.seedvault.restore.install.InstallModuleKt$installModule$1$3.invoke(InstallModule.kt:17)
02-16 12:47:38.908  5531  5531 E AndroidRuntime:        at com.stevesoltys.seedvault.restore.install.InstallModuleKt$installModule$1$3.invoke(Unknown Source:4)
02-16 12:47:38.908  5531  5531 E AndroidRuntime:        at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:53)
02-16 12:47:38.908  5531  5531 E AndroidRuntime:        at org.koin.core.instance.FactoryInstanceFactory.get(FactoryInstanceFactory.kt:38)
02-16 12:47:38.908  5531  5531 E AndroidRuntime:        at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:103)
02-16 12:47:38.908  5531  5531 E AndroidRuntime:        at org.koin.core.scope.Scope.resolveValue(Scope.kt:223)
02-16 12:47:38.908  5531  5531 E AndroidRuntime:        at org.koin.core.scope.Scope.resolveInstance(Scope.kt:211)
02-16 12:47:38.908  5531  5531 E AndroidRuntime:        at org.koin.core.scope.Scope.get(Scope.kt:193)
02-16 12:47:38.908  5531  5531 E AndroidRuntime:        at com.stevesoltys.seedvault.restore.install.InstallModuleKt$installModule$1$4.invoke(InstallModule.kt:17)
02-16 12:47:38.908  5531  5531 E AndroidRuntime:        at com.stevesoltys.seedvault.restore.install.InstallModuleKt$installModule$1$4.invoke(Unknown Source:4)
02-16 12:47:38.908  5531  5531 E AndroidRuntime:        at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:53)
02-16 12:47:38.908  5531  5531 E AndroidRuntime:        at org.koin.core.instance.FactoryInstanceFactory.get(FactoryInstanceFactory.kt:38)
02-16 12:47:38.908  5531  5531 E AndroidRuntime:        at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:103)
02-16 12:47:38.908  5531  5531 E AndroidRuntime:        at org.koin.core.scope.Scope.resolveValue(Scope.kt:223)
02-16 12:47:38.908  5531  5531 E AndroidRuntime:        at org.koin.core.scope.Scope.resolveInstance(Scope.kt:211)
02-16 12:47:38.908  5531  5531 E AndroidRuntime:        at org.koin.core.scope.Scope.get(Scope.kt:193)
02-16 12:47:38.908  5531  5531 E AndroidRuntime:        at com.stevesoltys.seedvault.App$appModule$1$10.invoke(App.kt:146)
02-16 12:47:38.908  5531  5531 E AndroidRuntime:        at com.stevesoltys.seedvault.App$appModule$1$10.invoke(App.kt:40)
02-16 12:47:38.908  5531  5531 E AndroidRuntime:        at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:53)
02-16 12:47:38.908  5531  5531 E AndroidRuntime:        at org.koin.core.instance.FactoryInstanceFactory.get(FactoryInstanceFactory.kt:38)
02-16 12:47:38.908  5531  5531 E AndroidRuntime:        at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:103)
02-16 12:47:38.908  5531  5531 E AndroidRuntime:        at org.koin.core.scope.Scope.resolveValue(Scope.kt:223)
02-16 12:47:38.908  5531  5531 E AndroidRuntime:        at org.koin.core.scope.Scope.resolveInstance(Scope.kt:211)
02-16 12:47:38.908  5531  5531 E AndroidRuntime:        at org.koin.core.scope.Scope.get(Scope.kt:193)
02-16 12:47:38.908  5531  5531 E AndroidRuntime:        at org.koin.androidx.viewmodel.factory.DefaultViewModelFactory.create(DefaultViewModelFactory.kt:11)
02-16 12:47:38.908  5531  5531 E AndroidRuntime:        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:187)
02-16 12:47:38.908  5531  5531 E AndroidRuntime:        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:150)
02-16 12:47:38.908  5531  5531 E AndroidRuntime:        at org.koin.androidx.viewmodel.ViewModelResolverKt.get(ViewModelResolver.kt:23)
02-16 12:47:38.908  5531  5531 E AndroidRuntime:        at org.koin.androidx.viewmodel.ViewModelResolverKt.resolveInstance(ViewModelResolver.kt:12)
02-16 12:47:38.908  5531  5531 E AndroidRuntime:        at org.koin.androidx.viewmodel.scope.ScopeExtKt.getViewModel(ScopeExt.kt:86)
02-16 12:47:38.908  5531  5531 E AndroidRuntime:        at org.koin.androidx.viewmodel.scope.ScopeExtKt.getViewModel(ScopeExt.kt:72)
02-16 12:47:38.908  5531  5531 E AndroidRuntime:        at org.koin.androidx.viewmodel.ext.android.ViewModelStoreOwnerExtKt.getViewModel(ViewModelStoreOwnerExt.kt:68)
02-16 12:47:38.908  5531  5531 E AndroidRuntime:        at com.stevesoltys.seedvault.restore.RestoreActivity$$special$$inlined$viewModel$1.invoke(ViewModelStoreOwnerExt.kt:75)
02-16 12:47:38.908  5531  5531 E AndroidRuntime:        at com.stevesoltys.seedvault.restore.RestoreActivity$$special$$inlined$viewModel$1.invoke(ViewModelStoreOwnerExt.kt:40)
02-16 12:47:38.908  5531  5531 E AndroidRuntime:        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
02-16 12:47:38.908  5531  5531 E AndroidRuntime:        at com.stevesoltys.seedvault.restore.RestoreActivity.getViewModel(Unknown Source:2)
02-16 12:47:38.910  5531  5531 E AndroidRuntime:        at com.stevesoltys.seedvault.restore.RestoreActivity.getViewModel(RestoreActivity.kt:19)
02-16 12:47:38.910  5531  5531 E AndroidRuntime:        at com.stevesoltys.seedvault.ui.RequireProvisioningActivity.onCreate(RequireProvisioningActivity.kt:54)
02-16 12:47:38.910  5531  5531 E AndroidRuntime:        at com.stevesoltys.seedvault.restore.RestoreActivity.onCreate(RestoreActivity.kt:22)
02-16 12:47:38.910  5531  5531 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:8071)
02-16 12:47:38.910  5531  5531 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:8054)
02-16 12:47:38.910  5531  5531 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
02-16 12:47:38.910  5531  5531 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3472)
02-16 12:47:38.910  5531  5531 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3683)
02-16 12:47:38.910  5531  5531 E AndroidRuntime:        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
02-16 12:47:38.910  5531  5531 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
02-16 12:47:38.910  5531  5531 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
02-16 12:47:38.910  5531  5531 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2108)
02-16 12:47:38.910  5531  5531 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
02-16 12:47:38.910  5531  5531 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:223)
02-16 12:47:38.910  5531  5531 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7948)
02-16 12:47:38.910  5531  5531 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
02-16 12:47:38.910  5531  5531 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:603)
02-16 12:47:38.910  5531  5531 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
the app starts and suddenly crashed. Does any one know how to prevent this from happening?

Thanks

**Comment by grote** [comment]
The relevant part of the log is:

```ruby
 java.lang.NoSuchMethodError: No static method getSupportedLocales(Landroid/content/Context;)[Ljava/lang/String; in class Lcom/android/internal/app/LocalePicker; or its super classes (declaration of 'com.android.internal.app.LocalePicker' appears in /system/framework/framework.jar!classes3.dex)
 E AndroidRuntime: at com.stevesoltys.seedvault.restore.install.DeviceInfo.(DeviceInfo.kt:12)
```

Which hints at a problem with the Android version. What Android version and fork/flavor you are using?

**Comment by beckietech** [comment]
hi @grote,

Thanks for pointing out, I checked out android11 version from github and my realme narzaro 50i shows Android main version 11, I don't know why it doesn't support.

In case that I might git it wrong, I also download android10 version testing on the same machine, and it crashes as usual and the logcat:
02-17 12:46:03.680 14011 14011 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.stevesoltys.seedvault/com.stevesoltys.seedvault.settings.SettingsActivity}: java.lang.UnsupportedOperationException: Can't convert value at index 1 to color: type=0x1
02-17 12:46:03.680 14011 14011 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3502)
02-17 12:46:03.680 14011 14011 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3683)
02-17 12:46:03.680 14011 14011 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
02-17 12:46:03.680 14011 14011 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
02-17 12:46:03.680 14011 14011 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
02-17 12:46:03.680 14011 14011 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2108)
02-17 12:46:03.680 14011 14011 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
02-17 12:46:03.680 14011 14011 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
02-17 12:46:03.680 14011 14011 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7948)
02-17 12:46:03.680 14011 14011 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-17 12:46:03.680 14011 14011 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:603)
02-17 12:46:03.680 14011 14011 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
02-17 12:46:03.680 14011 14011 E AndroidRuntime: Caused by: java.lang.UnsupportedOperationException: Can't convert value at index 1 to color: type=0x1
02-17 12:46:03.680 14011 14011 E AndroidRuntime: 	at android.content.res.TypedArray.getColor(TypedArray.java:533)
02-17 12:46:03.680 14011 14011 E AndroidRuntime: 	at android.app.Activity.onApplyThemeResource(Activity.java:5167)
02-17 12:46:03.680 14011 14011 E AndroidRuntime: 	at android.view.ContextThemeWrapper.initializeTheme(ContextThemeWrapper.java:216)
02-17 12:46:03.680 14011 14011 E AndroidRuntime: 	at android.view.ContextThemeWrapper.setTheme(ContextThemeWrapper.java:147)
02-17 12:46:03.680 14011 14011 E AndroidRuntime: 	at android.app.Activity.setTheme(Activity.java:5145)
02-17 12:46:03.680 14011 14011 E AndroidRuntime: 	at androidx.appcompat.app.AppCompatActivity.setTheme(AppCompatActivity.java:111)
02-17 12:46:03.680 14011 14011 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3460)
02-17 12:46:03.680 14011 14011 E AndroidRuntime: 	... 11 more
02-17 12:46:03.895   889  5559 E OplusAppStoreTraffic: InRegionList currentRegion = TW
02-17 12:46:03.896   889  5559 E ActivityTaskManager: executeRequest: trafficIntent =null
02-17 12:46:04.919 14044 14044 E AndroidRuntime: FATAL EXCEPTION: main
02-17 12:46:04.919 14044 14044 E AndroidRuntime: Process: com.stevesoltys.seedvault, PID: 14044
02-17 12:46:04.919 14044 14044 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.stevesoltys.seedvault/com.stevesoltys.seedvault.settings.SettingsActivity}: java.lang.UnsupportedOperationException: Can't convert value at index 1 to color: type=0x1
02-17 12:46:04.919 14044 14044 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3502)
02-17 12:46:04.919 14044 14044 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3683)
02-17 12:46:04.919 14044 14044 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
02-17 12:46:04.919 14044 14044 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
02-17 12:46:04.919 14044 14044 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
02-17 12:46:04.919 14044 14044 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2108)
02-17 12:46:04.919 14044 14044 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
02-17 12:46:04.919 14044 14044 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
02-17 12:46:04.919 14044 14044 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7948)
02-17 12:46:04.919 14044 14044 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-17 12:46:04.919 14044 14044 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:603)
02-17 12:46:04.919 14044 14044 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
02-17 12:46:04.919 14044 14044 E AndroidRuntime: Caused by: java.lang.UnsupportedOperationException: Can't convert value at index 1 to color: type=0x1
02-17 12:46:04.919 14044 14044 E AndroidRuntime: 	at android.content.res.TypedArray.getColor(TypedArray.java:533)
02-17 12:46:04.919 14044 14044 E AndroidRuntime: 	at android.app.Activity.onApplyThemeResource(Activity.java:5167)
02-17 12:46:04.919 14044 14044 E AndroidRuntime: 	at android.view.ContextThemeWrapper.initializeTheme(ContextThemeWrapper.java:216)
02-17 12:46:04.919 14044 14044 E AndroidRuntime: 	at android.view.ContextThemeWrapper.setTheme(ContextThemeWrapper.java:147)
02-17 12:46:04.919 14044 14044 E AndroidRuntime: 	at android.app.Activity.setTheme(Activity.java:5145)
02-17 12:46:04.919 14044 14044 E AndroidRuntime: 	at androidx.appcompat.app.AppCompatActivity.setTheme(AppCompatActivity.java:111)
02-17 12:46:04.919 14044 14044 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:34

Please tell me what's need to be taken care of? 
thanks

**Comment by beckietech** [comment]
hi @grote,

Could you elaborate your question - Which hints at a problem with the Android version. What Android version and fork/flavor you are using?

I also installed seedvault on my Realme(Andorid11) and the other mobile Koobee(Android10) and tried to find in Settings->System->Backup, but I don't see any entry to seedvault backup either. Must I use LineageOS or Stock Android also workable? what m I missing?

**Comment by grote** [comment]
You typically don't *install* Seedvault, it needs to come with the ROM and have the proper signature. So what Android version, Seedvault version and type of Android ROM are you using?

**Comment by beckietech** [comment]
hi, @grote,
No wonder, I'm using stock android without signature. I know it and now Im considering using custom ROM platform. May I know which one you're suggestion? Thanks

**Comment by grote** [comment]
I am very sorry, but the tracker is too full with unresolved issues to give custom ROM support here.
