### ISSUE TITLE
Seedvault forgot it had a Nextcloud backup setup

### ISSUE THREAD

**Issue by rugk** [stevesoltys/backup#382]
Seedvault just shows me the "setup screen" when I open the previous backed up screen and it warns me that old backups at the location will be deleted. So that's why I won't proceed for now.

However, if I had to guess now, the issue is likely because Nextcloud and that document storage framework just completely broke here: https://github.com/nextcloud/android/issues/9906

So I take this issue here mostly as a "users be aware" issue/for forwarding users to the upstream problem, and I guess it's a Nextcloud (or even OS?) fault.

## Logcat

I could find nothing in there…

```
[02-28 23:52:47.828 624:624 I/hwservicemanager]
Since vendor.qti.hardware.cacert@1.0::IService/default is not registered, trying to start it as a lazy HAL.

[02-28 23:52:47.829 1356:1391 I/HidlServiceManagement]
getService: Trying again for vendor.qti.hardware.cacert@1.0::IService/default...

[02-28 23:52:47.831 624:27716 W/libc]
Unable to set property "ctl.interface_start" to "vendor.qti.hardware.cacert@1.0::IService/default": error code: 0x20
```

Device: Pixel 4
OS: Android 12, CalyxOS 3.2.0
source: F-Droid
version: v12

**Comment by grote** [comment]
Looks like the Nextcloud screwed up its SAF badly. I suggest trying the DavX5 app against the Nextcloud server.

**Comment by rugk** [comment]
I am still trying to keep the Nextcloud people pushing to a (proper) fix actually… :upside_down_face: And their RC already seems to work good.

**Comment by grote** [comment]
ok so looks like nextcloud issue, closing here.
