### ISSUE TITLE
Existing Account not used, re-registered account not working...

### ISSUE THREAD

**Issue by IngwiePhoenix** [stevesoltys/backup#388]
Hello there!

I tried setting up SeedVault on my Razer Phone 2 with LineageOS 18.1 but I just can not get it to work...

Prior to thinking about setting this up, I set up the NextCloud app and my account with it. But when I tried to add NextCloud, I used the QR Code (Settings, Security, Create Password) and attempted to scan that. Yet, I still had to enter my username and password...

After the first attempt, I saw an error message saying that an account exists - so I removed the existing one, and tried again. After that, the account still did not seem to be registered. Instead, this keeps showing:

![Screenshot_20220315-143525_Seedvault](https://user-images.githubusercontent.com/2893716/158390112-6f9bad37-e1c1-46d5-a3a6-2c7f21387668.png)
![Screenshot_20220315-144426_Einstellungen](https://user-images.githubusercontent.com/2893716/158391226-0d424e16-4a1e-48e6-b605-e30d055b2e39.png)

Any idea? I am so lost... Is there something I need to set up on my server? Or am I missing something? I even completely deactivated my passcode (but not the fingerprint yet). I feel like error reporting is lacking, or rather I have no real idea where else to look but at the UI.

Thank you and kind regards. :)

**Comment by grote** [comment]
Looks like a NextCloud issue. Do you see the Nextcloud storage in the phone's files app? If not, Seedvault can't see it either and you need to resolve this with Nextcloud.

**Comment by IngwiePhoenix** [comment]
You are right - the option does not show up in the files app, it used to about a week ago when i set it up first.

Thank you for pointing this out, I'll look into this more.

**Comment by IngwiePhoenix** [comment]
Found the problem. If login via fingerprint or PIN is used, the content provider stops working.

So the error message displayed was halfway correct, it just lacked descriptiveness.

Instead of: "(oder deaktiviere passcode.)"
It should be: "(oder deaktiviere den in-app login.)"

I don't know what the english strings are for that, unfortunately.

Thank you for your help though :)
