### ISSUE TITLE
Ability to backup work profile app data

### ISSUE THREAD

**Issue by regaldude** [stevesoltys/backup#389]
Seedvault currently doesn't provide the ability to back up data for apps installed in work profile. 

As a workaround, i tried installing and running Seedvault in the work profile but the backups don't start for some reason.

**Comment by grote** [comment]
> Seedvault currently doesn't provide the ability to back up data for apps installed in work profile.

Why do you think so? It does work here.

**Comment by regaldude** [comment]
@grote I don't see the apps installed on my work profile while looking at the backup status from Seedvault

**Comment by grote** [comment]
I access mine from the main profile in settings and there I can select the main user or work profile after clicking "Backup".

**Comment by regaldude** [comment]
I don't get that option.

https://user-images.githubusercontent.com/63294824/159661090-d5d0a160-fd5c-4fe4-9e0a-33a4ade03eed.mp4

**Comment by grote** [comment]
It gives you the work profile option there as expected, but it looks like Seedvault hasn't been integrated correctly into your ROM. You should talk to the people building your ROM. Doesn't look like a Seedvault issue to me.
