### ISSUE TITLE
Backup always fails; ability to disable specific apps?

### ISSUE THREAD

**Issue by IngwiePhoenix** [stevesoltys/backup#394]
Hello!

So I noticed that just about all backups end with "Backup failed", and when inspecting in the menu, I can see that some apps like Aurora Droid, FakeStore and other apps installed as system apps seem to cause issues here.

Is there a way I can turn off the problematic apps? Or anything else I can do? I also saw that no new backups seem to made automatically... maybe it's because of this or do I always have to manually tap "Backup now"?

Thank you and kind regards,
Ingwie

**Comment by grote** [comment]
You can blacklist apps from backup in the app status overflow menu. However, to fix the underlying issue we would need a logcat from when a failing backup was running.
