### ISSUE TITLE
Missing backup unpacking and repacking Linux tool

### ISSUE THREAD

**Issue by chriswoope** [stevesoltys/backup#397]
It appears that this project doesn't provide any Linux tool to unpack and repack backups.

This is essential functionality because without it it's not possible to arbitrarily examine and manipulate backups and the data is effectively hostage to the Seedvault application (which, in turn, is the only way to read and write data on some non-rooted devices).

There is a third-party project https://github.com/tlambertz/seedvault_backup_parser but it seems like it's not updated to the current backup format.

**Comment by grote** [comment]
I don't consider it our responsibility to provide such a tool, but it is great that there is work under way to upgrade the existing tool: https://github.com/tlambertz/seedvault_backup_parser/issues/14

**Comment by khimaros** [comment]
worth noting that i'm waiting on https://github.com/seedvault-app/seedvault/issues/383 before starting work on this, as i don't have a good way to generate a small sample backup and my personal backups are too large to work with.
