### ISSUE TITLE
Seedvault still respects allowbackup on target SDK >= 31 apps

### ISSUE THREAD

**Issue by bill-myers** [stevesoltys/backup#401]
Seedvault uses FLAG_ALLOW_BACKUP to determine whether a package can be backed up.

However, due to the new "IGNORE_ALLOW_BACKUP_IN_D2D" compat change, the OS allows to backup packages anyway with that flag if they target SDK >= 31, but Seedvault doesn't know that.

Seedvault should query whether the IGNORE_ALLOW_BACKUP_IN_D2D compat change applies to the app and conclude that the app can be backed up if it does.

**Comment by grote** [comment]
duplicate of https://github.com/seedvault-app/seedvault/issues/165
