### ISSUE TITLE
Using mobile data on LineageOS 19.1

### ISSUE THREAD

**Issue by brianjmurrell** [stevesoltys/backup#405]
I have enabled Seedvault backup on my LineageOS phone which is now at 19.1 (Android 12).

Yesterday, Seedvault went through almost half of my monthly mobile data allowance.

I thought #291 was supposed to prevent that, but clearly it's not.  Or am I misunderstanding #291?

**Comment by brianjmurrell** [comment]
Any thoughts here?  Seedvault is still using up all of my mobile data.

**Comment by grote** [comment]
Can you provide a logcat of a Seedvault run when only mobile data is available. The system should only (force) schedule smaller key/value backups if I remember correctly and Seedvault should reject all backups when on metered connection.
