### ISSUE TITLE
Seedvault messes with ROM keys.

### ISSUE THREAD

**Issue by MajorP93** [stevesoltys/backup#408]
Hi,

so I took a Seedvault backup on LineageOS 18.1.
Transfered it to my phone after formatting data and flashing LineageOS 19.1.
I then restored the backup (I included pretty much everything in the backup and used experimental file restore feature).

System works after restoring but when you try to dirty-flash a new version on top of the system you will end up with a kernel panic and a log entry regarding keymaster error.

When flashing the LOS 19.1 ROM **without** restoring seedvault backup, the dirty-flash works without any problems and there is no kernel panic.

On a side node: the 18.1 ROM was signed with different keys than the 19.1 ROM.

I think a backup software should leave everything key-related untouched (vbmeta partition, vbmeta_system partition and everything else).

It would be greatly appreciated if you could look into it since apart from that I really enjoy using Seedvault!

**Comment by grote** [comment]
Seedvault just uses the AOSP backup mechanism and it doesn't intentionally mess with keys. Let us know if you have further info what exactly the problem is, e.g. what app is backup up and restoring what keys and what the exact error is after booting after restore.

**Comment by MajorP93** [comment]
So I found out this was caused by something else I did while developing the ROM.
Sorry for the consusion. It turned out it was not caused by seedvault.
This issue can be closed.
