### ISSUE TITLE
USBC SSD not being recognised

### ISSUE THREAD

**Issue by WhyNotHugo** [stevesoltys/backup#409]
I'm trying to use an external SSD for backups, but it seems it's not considered a valid option:

![image](https://user-images.githubusercontent.com/730811/169488469-f27ae20c-d858-4166-a1e7-9a5d615d0c30.png)

The UI _does_ say "USB flash drive", which I guess refers to a thumb drive and not an actual disk, but I don't think there's a technical different in how they communicate with the host. Shouldn't this work?

The drive is a [Samsung Portable SSD T5](https://semiconductor.samsung.com/consumer-storage/portable-ssd/t5/) and I'm using LineageOS 18.

**Comment by chirayudesai** [comment]
Do you see the drive in the "Files" app?

Perhaps it needs more power than the phone can provide over USB, or it has a filesystem that's not supported by the phone.

**Comment by WhyNotHugo** [comment]
> Do you see the drive in the "Files" app?

Nowhere obvious: not on the main screen nor on the hamburger menu.

> Perhaps it needs more power than the phone can provide over USB,

The disk LED does turn on, but that doesn't imply anything. I suspect that this might be the issue; any ideas on how to figure out if this is the case? I'm using a OnePlus 9.

> or it has a filesystem that's not supported by the phone.

It's a regular ext4 partition. Nothing fancy, no LUKS or anything alike.

**Comment by grote** [comment]
If it doesn't show in Files app, this isn't a Seedvault issue.
