### ISSUE TITLE
Lost Password, lost Backup?

### ISSUE THREAD

**Issue by philonmetal** [stevesoltys/backup#411]
Hello,

i didnt find anything in the FAQ.
I made a backup with seedvault on my phone (LineageOS). I use bitwarden to store my passwords, keyphrases and what not.
So for whatever reason, and i cannot explain it myself, i cant find my 12 words for restoring my backup.
Is there any possibility to restore at least my photos? For convinience my contacts would also be nice, but the fotos are my top priority.

Just to make things clear:
.) I do know that im on Github, posting in the bugreport section
.) I do know its my fault
.) I do know my request defys the purpose of an encrypted backup
.) And i do know that it might not be possible

But im desperate and if you cant help me, maybe you could point me in the right direction?

Sorry, and thanks!
Philipp

**Comment by grote** [comment]
Sorry, but if this were possible, Seedvault would not be secure and anybody could decrypt your backed up photos.

**Comment by philonmetal** [comment]
Thats what i thought!
Thank you!
