### ISSUE TITLE
Don't crash on SecurityException during restore

### ISSUE THREAD

**Issue by csicar** [stevesoltys/backup#413]
When restoring the a nextcloud backup from a `.SeedVaultAndroidBackup` with data from a SeedVault backup, SeedVault crashes with
"Failed to restore backup" (or sth. similar). Logcat shows the following:

(Token were replaced with pseudo values)

```
06-06 17:23:55.050 20298 20653 E RestoreCoordinator: Error while getting restore set 1337001
06-06 17:23:55.050 20298 20653 E RestoreCoordinator: java.lang.SecurityException: Invalid token '1337002' in metadata, expected '1337001'.
06-06 17:23:55.050 20298 20653 E RestoreCoordinator: 	at com.stevesoltys.seedvault.metadata.MetadataReaderImpl.decode(MetadataReader.kt:100)
06-06 17:23:55.050 20298 20653 E RestoreCoordinator: 	at com.stevesoltys.seedvault.metadata.MetadataReaderImpl.readMetadataV0(MetadataReader.kt:74)
06-06 17:23:55.050 20298 20653 E RestoreCoordinator: 	at com.stevesoltys.seedvault.metadata.MetadataReaderImpl.readMetadata(MetadataReader.kt:51)
06-06 17:23:55.050 20298 20653 E RestoreCoordinator: 	at com.stevesoltys.seedvault.transport.restore.RestoreCoordinator.getAvailableMetadata(RestoreCoordinator.kt:66)
06-06 17:23:55.050 20298 20653 E RestoreCoordinator: 	at com.stevesoltys.seedvault.transport.restore.RestoreCoordinator$getAvailableMetadata$1.invokeSuspend(Unknown Source:14)
```

The tokens (1337001, 1337002) match the names in the backup folder, with 1337001 being recently back-upped and 1337002 multiple months old.

Unfortunately I don't quite remember the origins of the old backup, but I would guess that it had a different encryption key.

### Workaround

You need to move the old backups (e.g. `.SeedVaultAndroidBackup/1337001`) to a different folder (e.g. `.SeedVaultAndroidBackupOld/1337001`)

---

This is kind of a user error, but I think crashing in this case is not the optimal response.

**Comment by grote** [comment]
@csicar do you still remember what had happened here? You manually copied backup files into a folder, but the wrong one? Or did you not touch the backup files at all and Seedvault messed up the tokens?

**Comment by grote** [comment]
The current code shouldn't crash due to the SecurityException, but it should not let the user continue, because the incident may be compromising security.
