### ISSUE TITLE
Recovery code setup and usage is impractical

### ISSUE THREAD

**Issue by schklom** [stevesoltys/backup#420]
1. The current recovery code can only be saved by manually writing down the words somewhere.
Password managers are great tools to save this code, but the code cannot be copy-pasted for some reason. Why? What is the benefit in not putting it into a textbox to copy it? Everyone nowadays know how to copy and paste text.

2. Typing the code for confirmation is also a hassle and prone to errors.
Those of us who use password managers likely do not care at all what the code is, we only care about the most important aspect: saving it and typing it.
Why do you make this process as difficult as possible?

Please at least add a simple alternative with a textbox or a button for copying the code, and a textbox for pasting the code.

**Comment by grote** [comment]
Thanks for your feedback. We are aware of the trade-offs and don't have any plans to change the recovery code process.
