### ISSUE TITLE
no restore because seedvault fails to see its folder

### ISSUE THREAD

**Issue by hubbty** [stevesoltys/backup#421]
Seedvault cannot restore because it doesn't see its own backup folder which is definitively there. I provided it on a thumb drive as well as on the device itself. Both were not found by Seedvault: [https://de.share-your-photo.com/2bcd67c17a](url)

This is what logcatreader recorded in the relevant timespan when internal (see screenshot) storage was chosen: https://bin.disroot.org/?8db20b28a846e936#JB21RbadXwscP5Tc8XqWSZHe85iyWYhwqndpAQbC6ogq

Seedvault is version 12-3.0

**Comment by grote** [comment]
```
[06-29 11:53:55.619 12165:12286 W/DocumentsProviderStoragePlugin]
Missing metadata file in backup set folder: 1649804812250

[06-29 11:53:55.619 12165:12286 W/RestoreStorageViewModel]
Location was rejected: content://com.android.externalstorage.documents/tree/primary%3A
```

Sounds like there's no metadata file in that folder.

**Comment by hubbty** [comment]
No there is no file called metadata or similar. Should there be one? I still have backups from other phones and none of them contains such a file. Nevertheless they have worked in the past.

**Comment by hubbty** [comment]
I was about to leave the house when I hastily posted my last reply and didn't look thoroughly enough. I did now find in two of those other backups these ".backup.metadata" files but not in the one that caused the problem.

It would be very helpfull if Seedvault would issue a meaningfull messsage in such a situation instead of a misleading one. The user would have a chance to correct the problem by looking for the file in other places where a copy of the backup would be.

**Comment by grote** [comment]
You are not supposed to mess with the `.SeedVaultBackup` files. So in the end, were you able to use those backups for restore?
