### ISSUE TITLE
Show foreground notification right away when doing manual backup

### ISSUE THREAD

**Issue by grote** [stevesoltys/backup#425]
Android 12 shows the notification only after some ~10s otherwise.

**Comment by theimpulson** [comment]
Need to use [setForegroundServiceBehavior](https://developer.android.com/reference/android/app/Notification.Builder#setForegroundServiceBehavior(int)) method on the said notification and set it to [FOREGROUND_SERVICE_IMMEDIATE](https://developer.android.com/reference/android/app/Notification#FOREGROUND_SERVICE_IMMEDIATE)
