### ISSUE TITLE
Add support for Proton Drive

### ISSUE THREAD

**Issue by ph00lt0** [stevesoltys/backup#432]
Please add support for Proton Drive (currently in Beta for Android)

**Comment by astarq** [comment]
Proton Drive is now out of beta and it would be great to see Seedvault add support for it!

**Comment by GitPudding** [comment]
Yes, support for Proton Drive would make backups so much easier and more accessible, especially for those who can't run their own server or don't want to pay to rent one from another service.

**Comment by Forage** [comment]
It looks like Proton Drive supports SAF:
https://www.reddit.com/r/ProtonDrive/comments/1581zp4/has_proton_implemented_storage_access_framework/
https://www.reddit.com/r/privacy/comments/108j3ud/protondrive_has_set_a_gold_standard_for_cloud/

Doesn't it @abjurato?

It would be great to see Seedvault allow the use of it.

**Comment by chirayudesai** [comment]
Unfortunately it looks like we won't be able to add it because the ProtonDrive app does not support `ACTION_OPEN_DOCUMENT_TREE` - which is what we need to store all the backup files.
