### ISSUE TITLE
Option to remove Seedvault 

### ISSUE THREAD

**Issue by Luchenta** [stevesoltys/backup#435]
Seedvault is buggy and keeps telling me there's an issue that needs to be fixed. Every day, multiple times. I had to write down it's appalling 16 word code to try to get it to stop, but it didn't. Stopping the app in settings doesn't work either. Please provide an APK to allow users to delete it so I can do so and not be pestered by this awful bloatware any more. I used to love Lineage, but this is seriously becoming too annoying to me.

**Comment by grote** [comment]
Removing this is a Lineage issues, not a Seedvault issue.

Here, we should figure out why on LOS, it is running even though it shouldn't. Ticket for this is https://github.com/seedvault-app/seedvault/issues/416
