### ISSUE TITLE
Backups fails if "App backup" is on.

### ISSUE THREAD

**Issue by ButteredCats** [stevesoltys/backup#438]
Hello,

I've found that after installing GrapheneOS, Seedvault backups now fail to backup my apps if the "App backup" setting is enabled. Without this it works completely fine. File backups also work fine regardless of this setting. Excluding all apps also didn't do anything to change this.

I'm on GrapheneOS version 2022082400 (Android 13) with Seedvault 11-2.3.

I was consistently able to get errors with adb logcat when this option was enabled.

[Seedvault logcat errors.txt](https://github.com/seedvault-app/seedvault/files/9438521/Seedvault.logcat.errors.txt)

**Comment by grote** [comment]
Seedvault 11-2.3 isn't meant to be used with Android 13. Like the name says, it is for Android 11 only. 

It is very outdated and contains known bugs as well as security issues. I am surprised that a security focused ROM would be shipping outdated software like this. You need to talk to them to get the latest version for Android 13.
