### ISSUE TITLE
[UX] Choosing backup step: Please add a confirm dialog + minor improvments

### ISSUE THREAD

**Issue by rugk** [stevesoltys/backup#444]
I was just running through the setup wizard and when I finally succeeded logging in into Nextcloud (which is quite hard if you have a proper password and 2FA enabled) I was at the setup screen with:
* a lot of backups, which I had to scroll
* ~~the most recent backup is at the bottom~~ they are ordered randomly(?) not by time (the most recent was the second last one, 
* the text (date of backup) is often not readable in full as it goes off-screen

So choosing the correct backup is hard, but even if you see it, as in my case, you may be too stupid to make it,´ and _fat-finger_ tap on the wrong one, which causes the following effect:
* it instantly starts restoring, which is bad as you notice your mistake right away
* when you press back to stop that wrong backuo from being restored to cancel the process, you _cancel_ the whole backup process, you cannot choose a different backup

## My proposals to solve this (solutions)
* somehow show the dates on a new line or so or offer a complete different UI
* maybe even automatically select the latest backup and make a simple "Yes, use this" / "No, let me choose a different backup" screen that goes first to ease the process (only offer manual selection as an alternative then)
* order that list, so the latest backup is listed at the start
* when in the selection dialog, add a confirm dialog that states the information again, so the user can cancel/see the backup being restored.

## Screenshot
(will be added in a second… backup's restoring… I better leave it untouched… :upside_down_face: )

**Comment by grote** [comment]
thanks for the feedback! I'd prefer one ticket per issue.

actionable here for me seems:

* ensure backups are sorted by time, newest at the top


what I am not sure about:

* confirmation dialog as it is one more click, but possible. on second thought, I'd rather implement backup selection, then you can just go back and select a different one.

**Comment by rugk** [comment]
Yeah feel free to split it for stuff you think makes sense. I just quickly wrote it together until I forget it.

**Comment by grote** [comment]
backups are now sorted by time, not sure when it happened, but within the last few months, also show time.
