### ISSUE TITLE
Put a big fat warning/info banner in the app or github page that this does not backup 'user data'

### ISSUE THREAD

**Issue by occb1978** [stevesoltys/backup#451]
Firstly, many thanks for all great work.

It would be nice if there is info in the app/wiki telling that this tool does not backup

Downloads, Music, Videos etc (i.e)` /storage/emulated/0`

(While no where in wiki it says it does backup `/storage/emulated/0` it gives an appearance that it does. 

(Alternatively, implementing this would also be great)

**Comment by chirayudesai** [comment]
It definitely lets you backup user data.

Open SeedVault, then scroll down till you see Storage Backup.

It'll let you select if you want to backup a selection or files, and also let you add folders.

**Comment by alpenamilch** [comment]
Can you provide some form of way to backup entire /storage/emulated/0  (except Android folder may be; assuming the new device will have already and mess up)

Often people have different folder structures. As a system baked in app, seedvault should have all access to storage
