### ISSUE TITLE
How to run added app in sandbox using adb command?

### ISSUE THREAD

**Issue by dream811** [stevesoltys/backup#452]
Sorry for the question, 
![image](https://user-images.githubusercontent.com/45660446/192430616-599bd63e-5470-4256-a515-c5b8722abe54.png)
I am looking for a adb command or any other way to run .

**Comment by chirayudesai** [comment]
That doesn't look related to SeedVault, not sure what exactly you want.

The only Contacts related thing here is a small local contacts backup helper, but that can only be called during backup.
