### ISSUE TITLE
"Backup now" is greyed out for DAV / Nextcloud

### ISSUE THREAD

**Issue by chirayudesai** [stevesoltys/backup#457]
Happens on Android 13

Internal storage is fine.

**Comment by Tealk** [comment]
I also have the problem, if you want me to test something let me know

**Comment by owzim** [comment]
Me too on `Calyx 4.2.0` and a `Pixel 4a`

I chose a webdav mount for my backup location. It in fact initializes the backup, I can see the seedvault files on my webdav server, but cannot run the backup, since `backup now` is greyed out.

**Comment by grote** [comment]
Upstream bug in CalyxOS: https://gitlab.com/CalyxOS/calyxos/-/issues/1266

**Comment by marek22k** [comment]
I still have the bug. What can I do?
![Screenshot_20240411-152412](https://github.com/seedvault-app/seedvault/assets/46723399/7eceaf5f-0b6a-4f2f-aa30-13084595a3be)

**Comment by marek22k** [comment]
I still have the bug. Is there a way to backup anyway?
![Screenshot_20240411-152412](https://github.com/seedvault-app/seedvault/assets/46723399/044b5564-e9cd-490f-a24a-7b2823700e7f)

**Comment by grote** [comment]
@marek22k can you export a logcat after force stopping seedvault and then opening it, going straight to Expert settings and then logcat export?

**Comment by marek22k** [comment]
Mystically, it is now clickable again. 🤷‍♂️ If it happens again, I will export the log and post it here.

**Comment by grote** [comment]
People having this issue, please check that you are not on a metered network (like mobile data you need to pay for). When you are, it is expected that 'backup now' is disabled.

**Comment by kylian-002** [comment]
I have ran in to this issue as well. I am using GrapheneOS on a Pixel 7 Pro. Build number is 2024042100
I am using mobile data with a unlimited data plan, how ever I have enabled unrestricted data access for Seedvault but still the backup now option has been greyed out.
