### ISSUE TITLE
Apps that don't allow data backup have their APKs backed up all the time, regardless of exclusions

### ISSUE THREAD

**Issue by t-m-w** [stevesoltys/backup#475]
Apps listed in Backup Status under "Apps that do not allow data backup" will have their APKs backed up, even if they are excluded by the user, and reinstalled during a restore.

This behavior does not happen for the APKs of excluded apps that *do* allow backup.

**Comment by grote** [comment]
Is this still relevant after #473?

**Comment by steadfasterX** [comment]
Excluding apps never works for me. Seedvault always seems to backup every single thing regardless what I set..

**Comment by grote** [comment]
should be fixed by https://github.com/seedvault-app/seedvault/pull/603
