### ISSUE TITLE
Back up fails on CalyxOS, to DavX on local Baikal

### ISSUE THREAD

**Issue by SolainOG** [stevesoltys/backup#486]
Hey, my setup in a baikal caldav running on a local server (this is configured correctly and works for every other application). On my pixel 4a 5g I have calyxos installed with seedvault builtin. The davx accounts are all set up and working. I chose to backup my apps and contacts via seedvault to the default davx account but the backup keep failing even when clicking "backup now". The notification for backup failed keeps popping up. Log included 
[seedvault-13-3.1-1671409591934.txt](https://github.com/seedvault-app/seedvault/files/10255035/seedvault-13-3.1-1671409591934.txt)
 Thank you :) happy to supply any additional info

**Comment by t-m-w** [comment]
Thanks for the report. Has the backup ever completed successfully? Your log shows repeated initialization failures, but from the log, I can't identify a reason for it. You may also want to look into any errors in server-side logs. SeedVault creates hundreds of directories and uploads a lot of files, so there may be some throttling or other exception being thrown at the server side that wouldn't happen in other use cases.

If you haven't had a successful backup yet, or don't feel you have any backup data to lose, can you try starting fresh and seeing how that goes?
1. Turn off "Backup my apps" in Backup (SeedVault).
2. Go to the App Info for SeedVault, and under Storage & cache, clear its storage.
3. Remove the .SeedVaultAndroidBackup folder from your WebDAV mount/server.
4. Open Backup (SeedVault), start over, and try backing up.
5. If it fails again, please save a log as soon as possible after the attempt. Feel free to send to bugreports@calyxos.org if you would rather share it privately.

**Comment by t-m-w** [comment]
Another useful thing to test, if you don't mind, mentioned in a different issue:
> Does trying to copy a bunch of files (perhaps even a SeedVault internal storage backup) work?
- https://github.com/seedvault-app/seedvault/issues/490#issuecomment-1368029558

**Comment by markcellus** [comment]
@t-m-w I'm not the original poster but I was having this same issue (just with Nextcloud backup instead of DavX) and it was resolved with your steps. Thanks a lot! 

It may be worth putting those steps on the README under a troubleshooting section or something since I've been seeing similar threads being created.

**Comment by grote** [comment]
@SolainOG could it be that your Baikal server is not allowing you to create the root `.SeedvaultAndroidBackup` directory?

**Comment by SolainOG** [comment]
@grote @t-m-w  it seems that baikal doesn't allow creation of files on the storage from my phone via any means (davx mounts and so forth). So I think the problem is with my baikal instance. 

Any idea why this is happening with baikal? Or recommendations for a webdav server with storage/mount support that was tested with seedvault? 

Thank you all very much

**Comment by jt196** [comment]
Baikal uses WebDav to sync calendars and contacts, but it isn't a WebDav server per se. 

I've had a look at a few and after some issues, found this very [simple Docker-based one](https://hub.docker.com/r/derkades/webdav) that seems to do the trick.

**Comment by jt196** [comment]
On second thoughts, try this [image](https://hub.docker.com/r/bytemark/webdav/#!), as per issue #500, nginx webdav doesn't seem to play well with seedvault due to the directory name. Apache WebDav looks like it's working.

**Comment by grote** [comment]
@jt196 could you try the new native WebDAV integration?

**Comment by jt196** [comment]
Hey @grote I'm afraid I moved onto vanilla Android on a Pixel a while back. Banking apps were the clincher unfortunately, they just weren't happy about working on Calyx.
