### ISSUE TITLE
Consider adding support for standalone builds

### ISSUE THREAD

**Issue by stevesoltys** [stevesoltys/backup#5]
Consider adding support for building this as a standalone application - without being included in AOSP.

This would give users who aren't interested in building AOSP the ability to install the APK as a system application whichever way they prefer.

**Comment by stevesoltys** [comment]
I have set up a branch which adds experimental support for this: https://github.com/stevesoltys/backup/tree/feature/standalone

I'm not too happy with including [these binary dependencies](https://github.com/stevesoltys/backup/tree/feature/standalone/app/libs) in the repository but they are required for building standalone. This should work for those interested in giving this a shot until I've come up with a more permanent solution.

**Comment by stevesoltys** [comment]
If anyone tries building and installing the standalone version as a system application, it would be helpful if you reported your results here. I don't have a device to test this on currently.

**Comment by stevesoltys** [comment]
I have a feeling this won't work since the service [probably needs to be whitelisted](https://github.com/stevesoltys/backup/blob/feature/standalone/app/src/main/whitelist_com.stevesoltys.backup.xml) but I'm still interested to see what happens.

**Comment by ale5000-git** [comment]
If one is able to write /system/priv-app it can also easily whitelist everything he want.

**Comment by stevesoltys** [comment]
That's true @ale5000-git. I'm not sure where whitelisted services exist in AOSP after build. Any idea?

**Comment by ale5000-git** [comment]
It should be similar to this: https://github.com/micro5k/microg-unofficial-installer/blob/master/zip-content/files/etc/sysconfig/microg-a5k.xml
but for whiltelist the backup provider (I haven't tried yet).

**Comment by stevesoltys** [comment]
@ale5000-git I tested installing the application and whitelisting the service / permissions in a debug build. Can confirm that standalone builds are functional.

Closed this since I've merged the branch into master.
