### ISSUE TITLE
Data not restored when reinstalling app

### ISSUE THREAD

**Issue by mikegilchrist** [stevesoltys/backup#511]
You can uninstall an app and then re-install it without Auto-Backup on. That will attempt to restore the app data from backup.

_Originally posted by @grote in https://github.com/seedvault-app/seedvault/issues/398#issuecomment-1108596154_

**Comment by mikegilchrist** [comment]
I'm running CalyxOS 4.5.0 on a Pixel 6a. I'm trying to restore my data by reinstalling an app (Nextcloud Notes, ICYC), but when I reinstall the app from f-droid, my data's not restored.  In #398  and the reference above it is stated this should happen "without Auto-Backup on". However, I don't see a "Auto-Backup" option in SeedVault's settings.  As a result, it's not clear if this is a setting within the app or withing the more general settings of the OS.  Can you clarify and/or reference.

**Comment by grote** [comment]
This is more of a questions for https://github.com/seedvault-app/seedvault/discussions than an issue report.

The options in settings is called "Automatic restore". When that is on, the system will attempt to restore app data on install from latest backup. However, for this, your backup storage needs to be accessible (network, server, etc.) and the app actually needs to have a proper backup. Check "Backup status" for this.

**Comment by mikegilchrist** [comment]
Thanks for the clarification.  It still doesn't work for me. I've posted a question on the discussion board.
