### ISSUE TITLE
Support Android Nextcloud Dev as alternative to mainline Nextcloud

### ISSUE THREAD

**Issue by sevmonster** [stevesoltys/backup#514]
Dev app implementation is identical to normal app implementation, just the app name and activities are changed to `com.nextcloud.android.beta`. It should be trivial to implement with the current setup.

**Comment by chirayudesai** [comment]
Perhaps we can implement this in a way where if it's installed, offer it as an option. If not, don't.

For restore that'd make things complicated since in some cases there'd be no easy way to install it.

**Comment by grote** [comment]
Since we now have native WebDAV support, I'd say not gonna happen
