### ISSUE TITLE
Infrequent backups

### ISSUE THREAD

**Issue by DamienCassou** [stevesoltys/backup#517]
Why does seedvault tells me that my last backup was 3 days ago? Why isn't it creating backup more regularly? In the last days, I received a couple of SMS text messages for example but they haven't been backup up yet (seedvault tells me that last backup of SMS was 4 days ago).

I'm using seedvault from LineageOS 18.1 from February 15 2023.

**Comment by grote** [comment]
This is more a discussion/question than a ticket.

Backup frequency is controlled by Android, not us. We are just a backup transport. It depends on many factors, such as network connection, battery level, device sleep, etc. Sometimes an app simply doesn't have changes to get backed up.

**Comment by stevleibelt** [comment]
@DamienCassou do you feel like @grote was able to answer your question?

If so, please close this ticket.

**Comment by DamienCassou** [comment]
Thank you for your answer @grote.
