### ISSUE TITLE
Behavior is user-hostile by enforcing mandatory unchangable size limit on backups and randomly excluding apps because it "wasn't used recently"

### ISSUE THREAD

**Issue by anymouse404** [stevesoltys/backup#525]
The "Backup Quota" is such a bizzare error message. There's absolutely no reason to enforce this for *local* backups. No given information about what the limit is, or possibility to give an app exception from it feels like an Apple approach of "we can't have our users hurting themselves".
Whatever the limit is, it is laughable because it can not possibly contain things like email history, offline maps, saved websites of a browser, graphics projects or big documents.

Same goes for "Not backed up as it wasn't used recently". Ehm, excuse me, don't you think that's for the *user* to decide? SeedVault just mandates that because I haven't used an app for a while, I do not need its data anymore?

**Comment by grote** [comment]
Seedvault needs to work within the limits of the AOSP backup API which has things such as quota and not backing up apps under certain conditions (check the FAQ). We already have an option to ignore the quota, but we can't do the same for backing up stopped apps without patching the OS itself.

**Comment by licaon-kter** [comment]
> check the FAQ

Which one?

> We already have an option to ignore the quota

What does an orange `i` icon mean for an app "too big" when "ignore quota" is toggled on?

**Comment by vbooka1** [comment]
I have a somewhat similar issue. Trying to run a backup, backup says "Not backed up as it wasn't used recently" for like 70% of all apps despite I actually use them. For the test I've force-closed 2 apps, opened them again, switched to the backup window and ran the backup again, and backup for these 2 apps did not succeed again - "Not backed up as it wasn't used recently".


> What does an orange `i` icon mean for an app "too big" when "ignore quota" is toggled on?

I have a red circle with `!` exclamation mark for one app that weights 8.2 GB. There is no any text message, just the icon.
I have more than enough free space for a local backup.

**Comment by vbooka1** [comment]
> I have a red circle with ! exclamation mark for one app that weights 8.2 GB. There is no any text message, just the icon.
> I have more than enough free space for a local backup.

And, of course, the "Unlimited app quota" checkbox is toggled on.
There is only one app with that red "!" circle, and this is the largest app on my phone. Maybe there is some hidden hardcoded limit for a single app like 4 GB maximum?
