### ISSUE TITLE
FAQ link in README uses relative link, broken in forks

### ISSUE THREAD

**Issue by m0byn** [stevesoltys/backup#533]
On [this](https://github.com/LineageOS/android_packages_apps_Seedvault) page in the second line of text it says one should read the FAQ. Well...the link does not lead to the FAQ!

**Comment by alpenamilch** [comment]
That page is lineageos repo. https://wiki.lineageos.org/how-to/bugreport

**Comment by theimpulson** [comment]
@m0byn, that repository is LineageOS. Please file an issue on their bug tracker if it is still valid. In any case, you can find the FAQ for seedvault [here](https://github.com/seedvault-app/seedvault/wiki/FAQ).

**Comment by chirayudesai** [comment]
@theimpulson The actual issue is usage of a relative link

Our FAQ: https://github.com/seedvault-app/seedvault/wiki/FAQ

It's valid for all forks too the most part.

It's linked as `[FAQ](../../wiki/FAQ)` - a direct link would fix this.
