### ISSUE TITLE
LineageOS: Sound recordings are not shown in recording app after restoration using Seedvault

### ISSUE THREAD

**Issue by m0byn** [stevesoltys/backup#534]
I restored a backup of my old phone on my new phone. After the restoration the sound recordings are not showing up in the app anymore. They are present in the folder, however. I suspect there might be some metadata lost? 

Is this the right place to post this issue? I suppose it is related to Seedvault, but not entirely sure...

**Comment by grote** [comment]
did you explicitly tell storage backup to backup the location of you sound recordings and turn on storage backup? Or did you expect Seedvault backup them up automatically?

**Comment by m0byn** [comment]
Thank you for responding. In LineageOS you can tick on to backup sound recordings. Then, I reinstalled LineageOS and used the backup created by Seedvault to restore everything. The sound recordings are backed up and shown in the respective folder (Recordings -> Sound records) BUT the recordings are NOT shown in the recordings app. So, I would argue that while backing up or restoring the phone, something happens to the recordings as they are not recognized by the recordings app anymore. Is it clear for you what I am trying to explain?

**Comment by grote** [comment]
Maybe raise the issue with the developers of the sound recording app, because I don't know what Seedvault could do differently here.
