### ISSUE TITLE
Add bells and whistles when backup sync breaks

### ISSUE THREAD

**Issue by uniqx** [stevesoltys/backup#537]
I've setup SeedVault (or actually "Backup" app on CalyxOS) to do backups to Nextcloud. My Nextcloud app (from F-Droid) seems to be working without any issues ever since I've set it up. However when I looked into SeedVault today to check if a particular app gets backed up or not, to my very big supersize I has to see that Seedvault didn't do any backups in 2 months!

I think there should be a very prominent warning when backups fail repeatedly!

**Comment by nettnikl** [comment]
This is depending on being able to even recognize this dangerous situation.
So, this depends on https://github.com/seedvault-app/seedvault/issues/290 imo.

**Comment by grote** [comment]
Can you please post or send the output of `adb shell dumpsys backup` (it may include data considered private)?

**Comment by uniqx** [comment]
I've sent the dump on a private channel.

**Comment by uniqx** [comment]
Okay, here are some more screenshots. So here's what my list app backups looks like right now:

<img src="https://github.com/seedvault-app/seedvault/assets/674081/75a791dd-0850-40f1-92f4-381559592a79" height="300" />

As you can see, a lot of apps are not getting backed up, they're in "waiting to get backed up ..." state.

Another peculiarity is that when I scroll through app backup status in SeedVault, I see "Waiting to back up ..." a lot. For only 4 apps I see "Backed up 21 hours ago". However in SeedVault settings it claims "Last Backup: 3 hours ago".

<img src="https://github.com/seedvault-app/seedvault/assets/674081/d4be66ce-a494-43c0-ae14-d86494803287" height="300" />

This is pretty confusing, I think it should track successful backups and backup attempts separately and display something that makes more sense ...

Inside my Nextcloud in the Uploads section there's a list of failed uploads from SeedVault. Juding from the error message it seems Seedvault might have already deleted the backup files, before Nextcloud had a chance to upload them?

<img src="https://github.com/seedvault-app/seedvault/assets/674081/5fb1fd37-b55d-4862-bcc7-913264c9184c" height="300" />

**Comment by grote** [comment]
@uniqx could you please try the built-in webdav feature instead of the nextcloud app? A lot mentioned here should be fixed in latest versions. E.g. we now show a notification after each backup, if it was successful or not.
