### ISSUE TITLE
log file during backup 

### ISSUE THREAD

**Issue by alpenamilch** [stevesoltys/backup#541]
A log file dumped into /storage/emulated/0 during running backup would be useful. For example, if backup or restore fails (yes, for me it fails when doing backup of /storage/emulated/0 in A11). 

- During storage backups may be can you put a message like <space occupied> GB/units. That way user knows if something useful did backup.

**Comment by albotroz** [comment]
Where is the seedvault log file at all? I need to see why Seedvaul tconstantly aborts the backup process via WebDAV (Davx5) to my server after a few minutes with a meaningless error message.

**Comment by chirayudesai** [comment]
SeedVault -> Menu (top right) -> Expert settings -> Save app log

**Comment by stevleibelt** [comment]
@alpenamilch so it looks like your issue is solved. Can you close it please?
