### ISSUE TITLE
audit link in FAQ wiki page is broken

### ISSUE THREAD

**Issue by Mynacol** [stevesoltys/backup#544]
The google backup audit link in the [FAQ](https://github.com/seedvault-app/seedvault/wiki/FAQ#why-do-some-apps-not-allow-to-get-backed-up) is broken. It seems nccgroup has moved the audit to another page. My search skills led me to this new URI: https://research.nccgroup.com/2018/10/12/public-report-android-cloud-backup-restore/

**Comment by grote** [comment]
thanks, fixed!

**Comment by provokateurin** [comment]
It is broken again.

https://www.nccgroup.com/us/research-blog/public-report-android-cloud-backuprestore/ seems to be the new link which looks quite similar to the archived version and features the same PDF: https://web.archive.org/web/20240625231031/https://research.nccgroup.com/2018/10/12/public-report-android-cloud-backup-restore/

**Comment by grote** [comment]
Should be fixed now, thanks @provokateurin !
