### ISSUE TITLE
Update theme setup for Gradle-only builds

### ISSUE THREAD

**Issue by theimpulson** [stevesoltys/backup#549]
The current setup is still using `AppCompat` themes as well as unavailable/unresolvable colors that result in UI looking bad on Gradle-only builds. It would be a good idea to refactor them to ensure we use officially available colors/API as well as Material3.

**Comment by grote** [comment]
@theimpulson is this still an issue?

**Comment by theimpulson** [comment]
This has been fixed. Closing the issue.
