### ISSUE TITLE
Don't backup & restore work profile owner / admin apps

### ISSUE THREAD

**Issue by grote** [stevesoltys/backup#560]
otherweise system zygote may crash when restore tries to reset its data

**Comment by chirayudesai** [comment]
Logcat

```
--------- beginning of crash
06-14 15:00:47.238  1000  1796 10659 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: unified-restore-engine
06-14 15:00:47.238  1000  1796 10659 E AndroidRuntime: java.lang.SecurityException: Cannot clear data for a protected package: org.calyxos.bellis
06-14 15:00:47.238  1000  1796 10659 E AndroidRuntime:  at com.android.server.am.ActivityManagerService.clearApplicationUserData(ActivityManagerService.java:3690)
06-14 15:00:47.238  1000  1796 10659 E AndroidRuntime:  at com.android.server.backup.UserBackupManagerService.clearApplicationDataSynchronous(UserBackupManagerService.java:1750)
06-14 15:00:47.238  1000  1796 10659 E AndroidRuntime:  at com.android.server.backup.UserBackupManagerService.clearApplicationDataBeforeRestore(UserBackupManagerService.java:1697)
06-14 15:00:47.238  1000  1796 10659 E AndroidRuntime:  at com.android.server.backup.restore.FullRestoreEngine.restoreOneFile(FullRestoreEngine.java:357)
06-14 15:00:47.238  1000  1796 10659 E AndroidRuntime:  at com.android.server.backup.restore.FullRestoreEngineThread.run(FullRestoreEngineThread.java:48)
06-14 15:00:47.238  1000  1796 10659 E AndroidRuntime:  at java.lang.Thread.run(Thread.java:1012)
06-14 15:00:47.240  1000  1796 10659 I DropBoxManagerService: add tag=system_server_crash isTagEnabled=true flags=0x2
```

**Comment by theimpulson** [comment]
Modified title to include "backup" as well as restore. We shouldn't backup apps if we aren't planning to restore them in first place.

**Comment by theimpulson** [comment]
Related convo: https://review.calyxos.org/c/CalyxOS/platform_packages_apps_Bellis/+/17659

**Comment by grote** [comment]
How do we find out if an app is a work profile owner or admin app?

**Comment by theimpulson** [comment]
> How do we find out if an app is a work profile owner or admin app?

How about using the [queryBroadcastReceivers](https://developer.android.com/reference/android/content/pm/PackageManager#queryBroadcastReceivers(android.content.Intent,%20android.content.pm.PackageManager.ResolveInfoFlags)) with [ACTION_DEVICE_ADMIN_ENABLED](https://developer.android.com/reference/android/app/admin/DeviceAdminReceiver#ACTION_DEVICE_ADMIN_ENABLED)?

Edit: Oh, work profile owner, not admin. I see DPM has [isDeviceOwnerApp](https://developer.android.com/reference/android/app/admin/DevicePolicyManager#isDeviceOwnerApp(java.lang.String)) and [isProfileOwnerApp](https://developer.android.com/reference/android/app/admin/DevicePolicyManager#isProfileOwnerApp(java.lang.String)) method. Not sure how well that works.

**Comment by grote** [comment]
These apps should be system apps and those should not allow backup. Android 14 still excludes them from backup in this case: https://cs.android.com/android/platform/superproject/+/android-14.0.0_r22:frameworks/base/services/backup/java/com/android/server/backup/utils/BackupEligibilityRules.java;l=191-197
