### ISSUE TITLE
How to restore work profile

### ISSUE THREAD

**Issue by Mynom** [stevesoltys/backup#571]
Is restoring the work profile (on another device) not really implemented yet?

It looks like shelter is creating a new profile (new 12 words)

And I cant find any option to "restore the work profile" before running shelter.

Am I missing something? Are there any tricks / adb commands to restore?

**Comment by grote** [comment]
I don't know about Shelter, but CalyxOS runs the setup wizard on new workprofiles that let's you restore.

Soon, we'll be implementing https://github.com/seedvault-app/seedvault/issues/309 which will help with this issue. However, we still need to figure out how to restore other backups made with different 12 words.

**Comment by grote** [comment]
> we still need to figure out how to restore other backups made with different 12 words.

thinking out load: when starting seedvault for the first time, we could ask whether the user wants to restore from a  previous backup or start fresh.

**Comment by tpreclik** [comment]
> > we still need to figure out how to restore other backups made with different 12 words.
> 
> thinking out load: when starting seedvault for the first time, we could ask whether the user wants to restore from a previous backup or start fresh.

So this would enable users eg. to clear seedvault's app storage, copy a seedvault backup dir maybe from a previous phone, start seedvault and restore from the backup directory without having to go through a full system restore? I'm all for it!
