### ISSUE TITLE
Backup to USB always fails

### ISSUE THREAD

**Issue by baschi29** [stevesoltys/backup#572]
Backing up to my USB-C USB stick always fails midway. This happens with manual full backup as well as with the automatic backup.

[Log](https://github.com/seedvault-app/seedvault/files/12822863/seedvault-13-3.3-1696535469556.txt) as a file as it's pretty long even after shortening it to the appropriate time frame.

Seedvault Version 13-3.3
Lineage OS 20 (20230924) on Oneplus 7t
Unlimited app quota is not enabled.

If you need more information, just tell me how to acquire it :)

**Comment by grote** [comment]
thanks for the report with log. unfortunately, the log was cut off too early. I'd need to see what happens afterwards. the actual failure happens later.

**Comment by baschi29** [comment]
My bad, [this](https://github.com/seedvault-app/seedvault/files/12908898/seedvault-13-3.3-1696535469556.txt) should hopefully be the unshortened log file. If not I will generate a new one with the same error later.

Edit: [here](https://github.com/seedvault-app/seedvault/files/12909625/seedvault-13-3.3-1697375337582.txt) is another completely unshortened log of the same problem.

**Comment by grote** [comment]
First one has this with no sign of issues:

```ruby
10-05 21:50:25.531  9778 11476 I NotificationBackupObserver: Backup finished 173/229. Status: -2003
10-05 21:50:25.531  9778 11476 D CompatibilityChangeReporter: Compat change id reported: 160794467; UID 10144; state: ENABLED
10-05 21:50:25.534  9778  9778 W BackupNotificationManager: Needed to clean up notification with ID 1
10-05 21:50:25.534  9778  9778 D ConfigurableBackupTransportService: Service destroyed.
10-05 21:50:25.534  1819 10205 I PFTBT   : Full data backup pass finished.
10-05 21:50:25.534  1819 10205 V BackupManagerService: [UserID:0] Released wakelock:*backup*-0-4972
```
The strange thing here is status `-2003` and then things just stop.

The second log has the same issue, but it gets to `217/271 - 80% - com.qualcomm.qcrilmsgtunnel`. So may be the same issue as https://github.com/seedvault-app/seedvault/issues/530
