### ISSUE TITLE
Move to our own scheduling

### ISSUE THREAD

**Issue by grote** [stevesoltys/backup#583]
We can now **disable framework scheduling of backups** via  `IBackupManager#setFrameworkSchedulingEnabledForUser()` and currently have these use-cases lined up for using our own scheduling:
   * not having to hack into backup API methods for doing things like APK backups
   * not trying to back-up when location is on flash drive
   * not trying to back-up when location is on local server while in different network
   * doing our  own scheduling, so we can control `BackupDestination` without OS patches
   * doing our  own scheduling, so users can get more control about when backups are done
   
Storage backups are already using their own scheduling.

**Comment by chirayudesai** [comment]
This could even be the `4.x` moment :)

**Comment by grote** [comment]
When exposing schedule settings in the UI, what should we allow the user to manually set?

* `repeatInterval`: 12 hours, 24 hours, 3 days, 1 week (specific times are harder and nothing for first iteration)
* `requiresCharging`: yes/no
* `requiresDeviceIdle`: yes/no (may be hard to explain what this means)
* `requiredNetworkType`: unmetered yes/no (maybe not even exposting as a toggle?)
* `requiresBatteryNotLow`: yes/no (may be in conflict with requires charging)
* `requiresStorageNotLow`: yes/no (probably not useful for most users)

I guess if we expose for than one or two, we'd introduce a new category for this on the main page? Or use a sub-page for scheduling settings?
