### ISSUE TITLE
Seedvault refuses to install apps from f-droid basic during restore on Android 14

### ISSUE THREAD

**Issue by wreps8Owt** [stevesoltys/backup#584]
May related to https://github.com/seedvault-app/seedvault/issues/78 and https://github.com/seedvault-app/seedvault/pull/502 .

I want to migrate data from another phone to a factory-resetted pixel 4a5g running GrapheneOS  2023101100 (Android 14), but Seedvault refuses to install apps obtained from [f-droid basic](https://f-droid.org/en/packages/org.fdroid.basic/) on the old phone ) during restore. It only allows me to launch the f-droid basic to install the app via "Tap to install" when it is present (install f-droid basic via adb first, and try to restore again, since it has the same key as the old phone now).

In order to complete the migration, I have to downgrade my pixel 4a5g to an older version (Android 13) first (via bootloader unlock, fastboot, and relock). In that version, apps can be successfully installed and data restored, and I can upgrade it to 2023101100 later.

**Comment by grote** [comment]
What is "user-trusted source" about? Is this a Graphene specific thing? How does "Seedvault refuses to install" look in practice? Can you post screenshots/photos?

**Comment by wreps8Owt** [comment]
> What is "user-trusted source" about? 

It is an app store installed by user, and allowed to "install unknown apps" by the user.

**Comment by grote** [comment]
maybe graphene OS is blocking installation somehow.

**Comment by Flunkyball** [comment]
I opened a different issue but our problem could be related. [https://github.com/seedvault-app/seedvault/issues/588](url)

I try exactly the same. Migration from a Pixel 7a (GrapheneOS, Android 14) to a Pixel 8 (GrapheneOS, Android 14).

In my case all apps fail to install, no matter if they are from F-droid or Aurora. I am presented with the same "Tap to install" option.

Actually, why cannot I find "Seedvault" under the "install apps from unknown source" tab in Android ? I would expect any app which will apks to be listed here but somehow Seedvault does not expose this permission...

**Comment by grote** [comment]
Is this still an issue on Graphene?
