### ISSUE TITLE
Back up non-backup or transferable apps with root 

### ISSUE THREAD

**Issue by upintheairsheep** [stevesoltys/backup#608]
Can you add the ability to back up apps that deny backups via normal and D2D via root? If the user has root and specifically chooses to back up those apps. It should pull its data folder excluding the cache and the code_cache and translate it into the Seedvault format, also possibly tweaking the APK of the app to allow D2D backups to allow it to be restored onto a non-rooted device. If it isn’t already backed up, the /sdcard/Android/(data/media)/(appID) of the specific app can be backed up on any device if the app prohibits both backups and D2D transfers.

It is also possible to backup and restore certain other data, such as /data/misc/adb/adb_keys.txt, containing the allowed ADB keys, and other settings files to investigate.

**Comment by grote** [comment]
Seedvault is all about not using root. Fake-D2D support was already merged.
