### ISSUE TITLE
Problems with restoring a backup using WebDAV in magentaCLOUD

### ISSUE THREAD

**Issue by dktzde** [stevesoltys/backup#622]
I am using LineageOS 20 on a Pixel 3 (64 GB)

I have created a backup via WebDAV (DAVx⁵) in MagentaCLOUD (TelekomDE). No problems with the backup.

When trying to restore on the same newly installed phone, I get an error message "wrong PW or memory error" (see screenshot).
I am sure I have entered my password correctly and next I am asked if I want to restore my data. As I have not created a data backup, no data is found.

What data could I provide to better understand the problem?

![Screenshot_20240213-130528_Seedvault](https://github.com/seedvault-app/seedvault/assets/12322609/e42caca8-9dc3-409c-bfa9-57a3ccf665bd)

**Comment by grote** [comment]
sorry, I am not sure I understand your issue.

> As I have not created a data backup, no data is found.

so you have not backed up anything before?

> When trying to restore on the same newly installed phone

what means newly installed phone? did you factory reset it? after backup?

> What data could I provide to better understand the problem?

logcat is always helpful, so would be the content of that magenta cloud. Is there a `.SeedVaultAndroidBackup` folder? if so, what is in it?

**Comment by dktzde** [comment]
Thank you for your quick reply.

> > As I have not created a data backup, no data is found.
> sorry, I am not sure I understand your issue.

I created a backup of my applications & application data. I have not backed up my user data.

> what means newly installed phone? did you factory reset it? after backup?

Before I had LineageOS. Then I wiped the phone and installed CalyxOS including factory reset.

> > What data could I provide to better understand the problem?
> logcat is always helpful, so would be the content of that magenta cloud.

Sorry I am not used to using logcat.

> Is there a `.SeedVaultAndroidBackup` folder? if so, what is in it?

See attached screenshot.
If you take a closer look, all the files are really small. Maybe there was a network problem when creating this backup.

Which brings me to another question:
How can I test/know if everything went well during the backup?

![signal-2024-02-14-13-23-19-937](https://github.com/seedvault-app/seedvault/assets/12322609/4182b536-9a28-4bc9-9cd7-5da35678eea3)

**Comment by grote** [comment]
> Sorry I am not used to using logcat.

It is built into seedvault. Open it, then at the top right, there's the menu, expert settings and then do log export.

>  If you take a closer look, all the files are really small. Maybe there was a network problem when creating this backup.

The first folder is most interesting. It is probably the magenta backup. Is there really only 1 KB worth of data inside?

**Comment by grote** [comment]
It looks like there may be an issue writing to that WebDAV provider. Some server-side DAV solutions may have issues. Can you copy files using your file manager to the DavX5 WebDav folder? It looks like everything that Seedvault manages to write has 0 bytes.

**Comment by dktzde** [comment]
I have tried to upload other files via WebDAV. These also have a size of 0 bytes. I will try to solve the problem with the support of the cloud provider.

**Comment by grote** [comment]
Thanks, then this is not a Seedvault issue. You may also involve the DavX5 devs as their app is probably used by other people on that cloud provider.

**Comment by grote** [comment]
Apparently, it was tested? https://www.davx5.com/tested-with/t-online

**Comment by dktzde** [comment]
See Issue at DAVx⁵ https://github.com/bitfireAT/davx5-ose/discussions/326
See Issue at Telekom: https://telekomhilft.telekom.de/t5/MagentaCLOUD/Upload-mit-DAVx5-in-die-MagentaCloud-produziert-leere-Dateien/m-p/6184427
In short: they know there is a problem. Maybe there will be a solution sometime.
