### ISSUE TITLE
Show system apps in Backup status

### ISSUE THREAD

**Issue by chirayudesai** [stevesoltys/backup#624]
At the moment, we don't show them at all.

We can't show all system apps since there's too many, and a lot of them don't even make sense to show (overlays, etc)

For a start, having just system apps with icons shown as a separate list at the bottom could work.

**Comment by chirayudesai** [comment]
Test: Especially after D2D, Chromium and friends / forks are able to get backed up and restored.

**Comment by grote** [comment]
When you say with icons, do you mean show/count all system apps with *launcher* icons?

**Comment by chirayudesai** [comment]
> system apps with *launcher* icons?

Yes

The idea being those are the apps easily visible

**Comment by grote** [comment]
Any idea how to identify those? Do we need to query all intent activities and then cache the list of packages with a launcher activity or given we have `PackageInfo` already, is there a way to find out if the package has a launcher activity?

**Comment by chirayudesai** [comment]
> Any idea how to identify those? 

`android.intent.category.LAUNCHER` would be my first pick.

I was thinking of the Firewall at first but that simply lists all system apps, which would lead to a long pointless list here.

Maybe another way is all system apps which have some data to back up, if that's easier. That then easily excludes a good chunk.

**Comment by dot166** [comment]
> > Any idea how to identify those?
> 
> `android.intent.category.LAUNCHER` would be my first pick.
> 
> I was thinking of the Firewall at first but that simply lists all system apps, which would lead to a long pointless list here.
> 
> Maybe another way is all system apps which have some data to back up, if that's easier. That then easily excludes a good chunk.

What about Launcher3? It (obviously) does not have an intent that has the `android.intent.category.LAUNCHER` catagory because it is the launcher. Also there is data that can be backed up from it (layout, wallpaper, icon pack (if applicable), etc).

**Comment by grote** [comment]
since https://github.com/seedvault-app/seedvault/pull/670, we now show (launchable) system apps in backup status as requested.
