### ISSUE TITLE
Apps that don't allow for backup cause backup failure

### ISSUE THREAD

**Issue by CurrentSubset68** [stevesoltys/backup#643]
Apps that don't allow for backup that cause errors for seedvault don't get automatically skipped. i had to manually exclude every one of these apps for seed vault to work again. i feel like these should be excluded by default unless device to device backup is enabled.
using the recently released calyx update.
I'll also list some Possible coincidences since i'm not too familiar with how the backend works:

- Could be low storage on my drive, but it has 32GB.
- I did disable backup limits, but reinabled it after i was backing up 600MB for some apps
- Could of accidentally fixed it by backing up one app, causing the app to reset (everything said waiting for backup)
- Randomly disconnected and reconnected at one point (maybe crashed the drive?)
- My drive is a recovery stick from a laptop company

**Comment by CurrentSubset68** [comment]
Possibly related to #575?
edit: just saw #635 as well

**Comment by grote** [comment]
What you describe does sound like a duplicate of #491, but without more information it is hard to say what exactly the issue(s) is/are you are observing.

As you need to eject the drive after using it, I already observed file system errors after not properly ejecting it which can cause issues with backing up as well.

**Comment by CurrentSubset68** [comment]
Thanks for the reply. I'll close it since another issue and a pull request exists for it.
