### ISSUE TITLE
Auto-pruning old snapshots when running out of storage

### ISSUE THREAD

**Issue by nickcalyx** [stevesoltys/backup#649]
Apple's Time machine ( which i've always thought was an elegant example to study ) works this way : 

1) Initially it makes a full backup
2) after that, it makes incrementals each hour ( in our case it could be more time )
3) When the disk starts to run out of space, Time machine starts deleting the oldest snapshots

I'd like to propose that we find a way to auto-prune ( after a opt-out of pruning notification ? ) old snapshots when the storage is running out of space

**Comment by grote** [comment]
https://github.com/seedvault-app/seedvault/pull/750 does auto-pruning after each backup run which maybe is preferable, because we have no reliable way to detect out of space situations on all storage backends.

**Comment by grote** [comment]
#750 is now merged and will ship with Android 15.
