### ISSUE TITLE
"Next backup: Never" string shows as untranslated variant on first app startup

### ISSUE THREAD

**Issue by lucasmz-dev** [stevesoltys/backup#651]
Device: moto g52 (rhode)
OS: CalyxOS 5.6.3
Language: PT-BR (Brazilian Portuguese)

The first time Seedvault is setup, if you're in another language, the string that says "Next backup: Never" is on English.
This seems to be undone if the string changes afterwards and changes back into it. Clearing app data doesn't seem to work for reproducing the issue.

# Steps to reproduce

1. Create a new user
2. Change language to one that has this string translated
3. Setup backups
4. "Next backup: Never" string is using the English variant.

<details><summary>Screenshots</summary>
<p>

First setup:
<img src="https://github.com/seedvault-app/seedvault/assets/55422065/d6d21a50-541b-47dd-9dbf-5e51ac40168d" width=25% height=25%>

String changed:
<img src="https://github.com/seedvault-app/seedvault/assets/55422065/5aaa762c-5e0b-4dd3-bd3c-caf58548f82f" width=25% height=25%>

String restored to "Never":
<img src="https://github.com/seedvault-app/seedvault/assets/55422065/a4f706ee-5a99-4a7b-b30c-20d3b22dff14" width=25% height=25%>

</p>
</details>

**Comment by grote** [comment]
Thanks for the report! Good catch!
