### ISSUE TITLE
[Feature Request] Allow individual apps to be restored.

### ISSUE THREAD

**Issue by dktzde** [stevesoltys/backup#653]
Similar to [#565](https://github.com/seedvault-app/seedvault/issues/565), I would like to be able to choose which applications to restore from a backup before (or during) the restore.

Background: I had forced F-Droid on a smartphone (LineageOS 20) with this customisation: [Extension - Workaround](https://forum.f-droid.org/t/privileged-extension-ota-workaround-for-los-17-1/11058) to install apps by itself. F-Droid was written to the backup, but both SeedVault and adb hang on F-Droid during restore. Unfortunately, I don't have an unused phone at the moment, so I can't test the restore process with logcat at the moment.

**Comment by grote** [comment]
Would be interesting to get the logcat of that restore hang. 

Otherwise, why is this ticket not a duplicate of #309?

**Comment by dktzde** [comment]
> Otherwise, why is this ticket not a duplicate of https://github.com/seedvault-app/seedvault/issues/309?

I overlooked it - it is.
