### ISSUE TITLE
Cannot use DAVx5 for restoring on new LineageOS 21.0 installation

### ISSUE THREAD

**Issue by DDvO** [stevesoltys/backup#683]
Seedvault offers the option to use the DAVx5 app for online backup storage.
This works fine when backup up data,
but how is this supposed to work to restore apps+data on a freshly installed system, where the DAVx5 apps is not (yet) installed?

In such a situation, one has to stop the phone setup procedure, manually install the app (and possibly further prerequisites such as a trusted CA certificate), and then use some of the workarounds mentioned here: https://github.com/seedvault-app/seedvault/issues/85#issuecomment-1620486863 to manually trigger the restore process again.

**Comment by grote** [comment]
> how is this supposed to work to restore apps+data on a freshly installed system, where the DAVx5 apps is not (yet) installed?

It is the OEMs responsibility to only allow backup providers that can also be used for restore. We ship an allow list config as an example.

CalyxOS for example has a setup wizard and tries to ensure that people can install DavX5 before the step of restoring backups.

> In such a situation, one has to stop the phone setup procedure, manually install the app (and possibly further prerequisites such as a trusted CA certificate), and then use some of the workarounds mentioned here: #85 (comment) to manually trigger the restore process again.

Yes, there's workarounds and we are even working on allowing you to restore at any later point. That said, I don't see anything actionable in this ticket.

**Comment by DDvO** [comment]
Thanks for your confirming response.

I see one actionable thing: approach those who integrated Seedvault into Lineage OS and point out to them that they should also provide some way of installing DAVx5 during/before restore. Since you are responsible for Seedvault, I suppose there are good chances that they listen to you. I'd suspect that you are in contact with them already.

> we are even working on allowing you to restore at any later point. 

That's appreciated! I guess you refer to that activity here:  #671

**Comment by grote** [comment]
> I see one actionable thing: approach those who integrated Seedvault into Lineage OS and point out to them that they should also provide some way of installing DAVx5 during/before restore. 

ping @mikeNG ^
