### ISSUE TITLE
Show full backup location, particularly for WebDAV

### ISSUE THREAD

**Issue by t-m-w** [stevesoltys/backup#690]
As I've been testing things, I have a device which is set to use WebDAV and a particular server, but I cannot remember the full backup location it's set to use, and I cannot view it. All I can see in the Seedvault settings preference for Backup location is "WebDAV [hostname]". Being able to see the full path would be useful for me in this case.

(Also being able to see the username would be useful, but that's a bonus.)

**Comment by t-m-w** [comment]
Replying re the pull request here:

> Showing just the host is good for most people, I'd say and showing the full path may be ugly and un-needed in case of Nextcloud, so not sure this change is good./

An alternative specifically for WebDAV could be to allow the parameters to be edited...? That could be a good change, anyway. What happens now if the user's password changes? Do they have an opportunity to update it, or do they get an unexplained failure and need to reinitialize the backup location? (Guess I could test that.)

**Comment by grote** [comment]
> An alternative specifically for WebDAV could be to allow the parameters to be edited...? 

Not sure. If you edit them, in most cases they will be for a new location and this you can already setup. If they are similar to the old ones, editing would be a small convenience, but we'd probably kick of the same process as setting a new location anyway.
