### ISSUE TITLE
Backup must not blindly consume all storage space

### ISSUE THREAD

**Issue by DDvO** [stevesoltys/backup#698]
Seedvault so far does not care about available storage space.
This has two bad consequences.
* The backup process fails in the middle of activity, with no possibility anymore to react sensibly on this. 
It should determine beforehand if the available space will sufficient and warn accordingly in case it is going to get tight, asking if/how to proceed. 
* Even worse, when local phone space gets filled up entirely, even system Android apps can no more run properly, which easily blocks the whole phone!
You should leave a safety margin of, e.g., 500 MB, as sensible storage-intense apps like the Camera do.

**Comment by grote** [comment]
> Seedvault so far does not care about available storage space.

Not true. Latest version doesn't do backups when not enough space available: https://github.com/seedvault-app/seedvault/pull/656

**Comment by DDvO** [comment]
Good to learn that this issue has recently been (more or less) solved.

How to update the Seedvault instance shipped with current LineageOS 21, which so far has version 14-4.0?

**Comment by julianfoad** [comment]
For tangential questions consider using the discussion room, https://matrix.to/#/#seedvault-app:matrix.org

**Comment by DDvO** [comment]
Thanks @julianfoad for this hint.
Yet in that room I did not find an answer to my question (using the simple text search feature of Element).

https://github.com/seedvault-app/seedvault/wiki would be a better place for such information.
