### ISSUE TITLE
Clarify misleading UI message "Existing backups in this location will be deleted"

### ISSUE THREAD

**Issue by julianfoad** [stevesoltys/backup#701]
This UI message "Existing backups in this location will be deleted" when selecting a backup location is both scary and, in present versions, wrong. We may not know exactly what we want in the end but we should try to make it more factually accurate and helpfully guiding.

- Should explain that SV won't try to delete existing backups here, saved by other devices using SV, or with previous keys from this same device, but that they *might* be deleted by some (older) versions of SV or other backup utilities. Grote wrote:
  > The UI message comes from the fact that we are wrestling with the undocumented AOSP backup API. It wants us to delete backup data when initializing a new backup, but we deviate from it, but haven't always.

- Should explain it's OK to share a backup location with other devices.

- I'm getting the feeling the semantics around multiple devices backing up to same location might get somewhat entwined with the issues about pruning backup history from one device (#99, #100, #566,...), and need to be considered together if this is a supported scenario.

**Comment by grote** [comment]
We'll remove this message in the next big version as we won't delete backups anymore.

**Comment by grote** [comment]
Since #750 we are not deleting old backups anymore when choosing storage location.
