### ISSUE TITLE
Seedvault - No option to restore a backup on AndroidTV Devices

### ISSUE THREAD

**Issue by mo123** [stevesoltys/backup#706]
Currently there is no way to open Seedvault app on custom AndroidTV devices eg. LineageOS ATV on Raspberry Pi4.
It uses the TvSettings app that doesn't have a backup menu instead of the Settings app used by phones, tablet that have a backup menu.
https://github.com/LineageOS/android_packages_apps_TvSettings
I don't think anyone will be able to port or create a new Backup/Restore menu for TvSettings compatible with Seedvault.

If you open the app through TvSettings' App menu it opens the backup settings of Seedvault but there is no place to open the restore settings.
Storage permissions are also not granted automatically and you have to enable it manually in TvSettings' Apps menu for the app to can open.
AndroidTV devices also don't have Contacts, Messages etc. that try to get backed up.
Device Settings seem to also get backed-up even if not selected.
It takes a bit long to enter 10 words on AndroidTV devices with a remote, anyway to reduce it to 3-5 words?

Perhaps a "android.intent.category.LEANBACK_LAUNCHER" intent can be added so that Seedvault shows an app banner on AndroidTV devices but not on phones, tablets that use "android.intent.category.LAUNCHER"

If anyone can build a testing app with better compatibility for AndroidTV 12 devices, it would be great to test.

**Comment by grote** [comment]
> If you open the app through TvSettings' App menu it opens the backup settings of Seedvault but there is no place to open the restore settings.

This should get solved by https://github.com/seedvault-app/seedvault/issues/671

> Storage permissions are also not granted automatically and you have to enable it manually in TvSettings' Apps menu for the app to can open.

How was Seedvault integrated into AndroidTV? Usually, it needs to be build into the ROM. What AndroidTV TOM have you been using? If it was Lineage, maybe they need to fix the permission issue on their side.

> AndroidTV devices also don't have Contacts, Messages etc. that try to get backed up.

Is there any issue with this?

> Device Settings seem to also get backed-up even if not selected.

What do you mean by selected? Are you manually excluding device settings from backup?

> It takes a bit long to enter 10 words on AndroidTV devices with a remote, anyway to reduce it to 3-5 words?

No sorry, less than 12 words wouldn't be secure anymore.

I am curious: What on the TV device actually does get backed up that  is worth having backups of? Did you ever test restore?

**Comment by grote** [comment]
Closing this as restore from ui is now enabled.
