### ISSUE TITLE
Status bar icon hide/show settings should be backed up

### ISSUE THREAD

**Issue by lucasmz-dev** [stevesoltys/backup#707]
Status bar icon hide/show settings do not seem to be backed up by Seedvault.

Wording is a bit confusing. I mean these:
![Screenshot_20240709-110116](https://github.com/seedvault-app/seedvault/assets/55422065/d5dd2154-ef93-405d-98a0-6fb9cdef1565)

**Comment by grote** [comment]
While counter-intuitive, it is not actually up to Seedvault to back this up, it just receives data from the OS per app. So the settings app (or some app related to settings) is responsible for this.

The feature may be an non-AOSP patch by the ROM you are using, so you needreport to the rom. CC @chirayudesai

**Comment by lucasmz-dev** [comment]
I wasn't even gonna report this but nick asked lol, but now thinking about it, I'm not sure if this issue was just between LineageOS/CalyxOS switching or also when just using backups in CalyxOS.
