### ISSUE TITLE
Signed tags / releases

### ISSUE THREAD

**Issue by chirayudesai** [stevesoltys/backup#741]
We haven't done it for a while, but I just tagged the latest `android14` release, before we made the `android15` branch. https://github.com/seedvault-app/seedvault/releases/tag/14-4.1

**Comment by chirayudesai** [comment]
Now, the main thing here is - should we go back and tag the missing versions in between? I filed this issue mainly for that.

If so, going to list the tag points below.

Related: https://github.com/seedvault-app/seedvault/issues/188

**Comment by chirayudesai** [comment]
Missing tags and the commits which modified CHANGELOG:

| Commit | Message | CHANGELOG.md | AndroidManifest.xml |
| ------ | ------- | ------------ | ------------------- |
| 9097c8ce | Bump version to 14-4.0 - D2D <3 | :heavy_check_mark: | :heavy_check_mark: |
| e6f32510 | Bump version to 14-3.3 | :heavy_check_mark: | :heavy_check_mark: |
| eebeff90 | Bump version to 13-3.3 | :heavy_check_mark: | :heavy_check_mark: |
| 4520ed4f | Bump version to 13-3.2 (#487) | :heavy_check_mark: | :heavy_check_mark: |
| 4e0fab18 | Bump version code and version name (13-3.1) | :heavy_check_mark: | :heavy_check_mark: |
| e9729569 | Android 12 - 12-3.0 | :heavy_check_mark: | :heavy_check_mark: |

**Comment by grote** [comment]
Since you already identified the commits, we may as well tag them.

**Comment by chirayudesai** [comment]
> Since you already identified the commits, we may as well tag them.

Ok, updated the comment, mind quickly double-checking to see if those look ok? Thanks!

**Comment by grote** [comment]
look alright to me, thanks!

**Comment by chirayudesai** [comment]
Done, 6 tags pushed.
