### ISSUE TITLE
Back stack handling may cause display of outdated state

### ISSUE THREAD

**Issue by t-m-w** [stevesoltys/backup#751]
In some circumstances, the "Included files and folders" page of Storage Backup might incorrectly show an outdated state of the categories toggles, even if one or more had been turned on previously. Tapping to turn on one category updates the state of the rest of them; e.g., if they were all turned on before, the others will correctly appear to be turned on again immediately after tapping one of them.

I think this is related to launching Seedvault from the notification, which appears to create another instance of the Seedvault activity.

Steps to reproduce (untested, guessing):
1. Open Seedvault.
2. Start a backup.
3. In Seedvault settings, visit the "Included files and folders" page under the Storage Backup section. Turn on Storage Backup first if needed.
4. Note the category toggles, e.g. all off.
5. Remain on this page. Wait for the backup to finish.
6. When the backup finishes, tap the finish notification, which will open Seedvault settings.
7. Navigate to the "Included files and folders" page again. This time, alter at least one of the toggles. 
8. Navigate back a few times, and you should end up at the "Included files and folders" page again.

Expected result (untested, guessing):  
The page properly represents your recently-changed settings.

Actual result (untested, guessing):  
The page shows the state of the toggles from before you changed them. Changing one toggle will refresh it.

*Possibly* related somehow (because I am including this): https://github.com/seedvault-app/seedvault/pull/750

**Comment by t-m-w** [comment]
This might affect more than just category toggles and the storage backup page. If possible, having the backup notification not launch a new instance may help -- assuming that's what's happening.

**Comment by grote** [comment]
@theimpulson using the navigation library *may* help with this.

**Comment by grote** [comment]
@t-m-w when you get the chance may be nice to try this again with latest https://github.com/seedvault-app/seedvault/pull/750 to see if it still happens there. It may not.

**Comment by t-m-w** [comment]
The steps provided no longer reproduce this issue. Tapping the backup notification brings up the existing Seedvault window if any - no more duplication. It no longer takes you to the backup status screen if Seedvault was already open, unless you were already there. This means "Tap to learn more" won't necessarily directly help you "learn more" now, but that's a separate problem. This problem itself is solved.
