### ISSUE TITLE
Snapshot display improvements

### ISSUE THREAD

**Issue by t-m-w** [stevesoltys/backup#753]
Enhance the backup selection's snapshot display:
1. [x] Include number of apps and their size
2. [x] Include number of apps with data and the data size
3. [ ] Possibly include Android version
4. [x] Do not show backup size if version is <2 and size is determined to be 0 B, since this doesn't necessarily represent a problem (restore might work just fine), but showing "0 B" will always appear to be wrong.

(Taken from [this and nearby comments](https://gitlab.com/CalyxOS/calyxos/-/issues/2708#note_2132019340))

**Comment by grote** [comment]
Let's wait with showing the Android version until we find a need for it.
