### ISSUE TITLE
Keyboard covers up recovery code entry

### ISSUE THREAD

**Issue by t-m-w** [stevesoltys/backup#754]
The recovery code entry screen no longer adapts to show input fields that would otherwise be under the keyboard. This happens when restoring a backup or when verifying the recovery code - inside and outside of the Setup Wizard.

[screen-20240926-170403 (trimmed).webm](https://github.com/user-attachments/assets/310b8ad4-29aa-46ea-ae9b-cbe9fdfd3e4d)

Pretty sure (but not entirely sure) that this is caused by https://github.com/seedvault-app/seedvault/pull/750 because I do not see it in CalyxOS 5.11.2.

**Comment by grote** [comment]
> Pretty sure (but not entirely sure) that this is caused by #750 because I do not see it in CalyxOS 5.11.2.

We didn't really change anything there. More likely is an Android 15 and/or library upgrade behavior change.

**Comment by grote** [comment]
@theimpulson could your edge to edge changes have caused this?

**Comment by grote** [comment]
Yeah that was it. @theimpulson's code didn't account for the IME insets.  Something to keep in mind when testing this kind of change: always try the keyboard!

**Comment by t-m-w** [comment]
Can confirm this is fixed in latest app-backup-v2!
