### ISSUE TITLE
Backup restored apps "Installed from" show as microG companion

### ISSUE THREAD

**Issue by lucasmz-dev** [stevesoltys/backup#756]
After restoring my backup from/to CalyxOS 5.11.2, apps installed from Aurora Store show as installed from microG companion (which is the same package that pretends to be the Play Store).

This breaks unattended updates.

**Comment by grote** [comment]
I think this is a CalyxOS "installer masquerading" issue and needs to be reported there. Only if the "installed from" would not get restored at all, it would be a Seedvault issue.

**Comment by grote** [comment]
Follow-up question: have you actually tried to update a restored app? was auto-update verifiably broken?

**Comment by lucasmz-dev** [comment]
> Follow-up question: have you actually tried to update a restored app? was auto-update verifiably broken?

Yep

**Comment by grote** [comment]
adb shell pm dump $pkg

Both before and after should tell us what's wrong. But this should really go into a ticket for calyxOs, needs creating if none exists, yet.

**Comment by lucasmz-dev** [comment]
FYI it is just the first update; not anything after, after that it just says installed by Aurora and that works fine from then on.

**Comment by grote** [comment]
upsream ticket: https://gitlab.com/CalyxOS/calyxos/-/issues/2171

> FYI it is just the first update; not anything after, after that it just says installed by Aurora and that works fine from then on.

that's the expected behavior, but the first update should still not need confirmation.
