### ISSUE TITLE
How to select the apps to backup?

### ISSUE THREAD

**Issue by guy-teube** [stevesoltys/backup#757]
Hi there,
Is it possible to select the apps to backups?
I have ~4Gb of space on my host. The next offer with 10Gb is more expensive (and I wouldn't like to change of host).
Bu in the notification, I see apps like Google apps, or already installed by default with the OS (LineageOS in my case). I don't want to backup these apps, because if I change of phone, they will be provided with the OS. I only want to backup the installed apps (and no all of them).
I think if I could select them, the backups would take up less space, and fit my 4Gb offer, so I wouldn't need to change of offer or host.
I hope it is / will be possible?
Thank you

**Comment by grote** [comment]
Please use the discussions for questions.

You need a recent version of Seedvault to be able to select apps for restore. see https://github.com/seedvault-app/seedvault/blob/android15/CHANGELOG.md

**Comment by grote** [comment]
you can exclude apps from getting backed up in settings, backup status, 3-dot overflow menu.

**Comment by guy-teube** [comment]
Sorry for posting in the wrong section.
Thank you for the answer.
I've just updated my system, and now I have 14.4.1 version, with the exclude function.
Thanks a lot for your work! ❤️
