### ISSUE TITLE
Seedvault was closed in the middle of restore; now what?

### ISSUE THREAD

**Issue by t-m-w** [stevesoltys/backup#759]
The user can swipe away Seedvault when it is in the middle of reinstalling apps or restoring data.

If they do this, Seedvault continues to display a "Restore running" notification, even if it stops functioning.

If it's reinstalling apps, I observed that these apps continue to be reinstalled in the background, but the user cannot see any progress.

If it's restoring data, I observed that sometimes the process will fully complete and sometimes not.

I don't know *what* to do about this, but perhaps something.

**Comment by grote** [comment]
> The user can swipe away Seedvault when it is in the middle of reinstalling apps or restoring data.

swipe away in the sense of kill the app from the carousel viewer of recent apps? Apart from the force stop button in app settings, I think this is the only the the user can kill the app. So not sure what we can do about that. Maybe the user shouldn't have killed the app in the first place?

> If it's reinstalling apps, I observed that these apps continue to be reinstalled in the background, but the user cannot see any progress.

May be possible to make the notification clickable and bring them back to showing progress.

**Comment by grote** [comment]
With #750 we now do what we can to recover from this.
