### ISSUE TITLE
TikTok doesn't show up in the app list, but is backed up anyway

### ISSUE THREAD

**Issue by lucasmz-dev** [stevesoltys/backup#769]
I have [TikTok](https://play.google.com/store/apps/details?id=com.zhiliaoapp.musically) installed, for some reason when going into Seedvault > Backup status, it cannot be found. It is also not possible to remove it from being backed up.

TODO: try and get logs

OS: CalyxOS 5.11.2
Seedvault version: 14-4.1

**Comment by lucasmz-dev** [comment]
I didn't even notice this I thought it was just some other bug, but TikTok stores a LOT of data, and that makes the backup be considerably larger, at least on D2D, I just thought it was just some miscalculation originally like not counting APKs, but I guess it is this.

**Comment by grote** [comment]
Can you post a screenshot of Tiktok's app details page from system settings? Also a screenshot of backup status of where tiktok would be, may be nice.

**Comment by grote** [comment]
Ok, it isn't shown, because it ships instrumentation tests in its production build: https://developer.android.com/guide/topics/manifest/instrumentation-element

Normally, we'd been hiding those, because on our dev phones these instrumentation test apps are not real apps and shouldn't be shown in the list.

**Comment by grote** [comment]
It is a test package for `com.bytedance.forest` and has some interesting split names:

    [config.arm64_v8a, config.en, config.xxhdpi, df_kakao, df_line, df_line_nonus, df_location, df_location.config.arm64_v8a, df_oppo_push, df_oppo_push.config.en, df_search_adblock, df_tiktok_font, df_transsion]
