### ISSUE TITLE
Doesn't perform storage backup on initial backup to flash drive

### ISSUE THREAD

**Issue by An-anonymous-coder** [stevesoltys/backup#770]
1. Format a flash drive
2. Go to Settings > System > Backup
Ensure storage backup is enabled by selecting "Backup my files"
Ensure D2D backup is enabled in Expert settings > Device-to-device backups
5. Open "Backup location"
6. Select your formatted flash drive

After the backup initializes it will only perform a device backup. It will not perform a storage backup until the next backup. 

Port of this issue: https://github.com/GrapheneOS/os-issue-tracker/issues/4049

**Comment by grote** [comment]
@t-m-w during your recent testing, could you reproduce this?

**Comment by grote** [comment]
After storage location was changed to a USB drive, we automatically kick off a backup: https://github.com/seedvault-app/seedvault/blob/5f8e85944a0ae156b8850f2f03267193cca90856/app/src/main/java/com/stevesoltys/seedvault/ui/storage/BackupStorageViewModel.kt#L83

However, it indeed looks like file backup isn't included.
