### ISSUE TITLE
Does SeedVault backup the Android user dictionary?

### ISSUE THREAD

**Issue by Diapolo** [stevesoltys/backup#783]
I need to reinstall CalyxOS as I need to abandon root access (because of so many stupid root-detection stuff in banking etc. apps). Now I'm asking how to backup and restore the Android user dictionary, as TitaniumBackup likely will not work anymore.

Does SeedVault include the dict in the user settings and what exactly is included in the user settings?

Thanks
Dia

**Comment by grote** [comment]
Please use the https://github.com/seedvault-app/seedvault/discussions for questions!

Seedvault only backs up what it receives from the apps and the system. The apps are responsible for what to give. Seedvault doesn't decide (and can't access) data on its own. So you need to ask the app dev of that dictionary.

**Comment by Diapolo** [comment]
@grote It's the integrated one and no extra app... so my guess was it could be included in the system settings backup. Which is what I also asked for... what is backed up ;-).

**Comment by grote** [comment]
still an app developer or ROM question. Not Seedvault's business.

**Comment by grote** [comment]
ROM ticket for whose who want to follow on: https://gitlab.com/CalyxOS/calyxos/-/issues/2787
