### ISSUE TITLE
.backup.icons and .backup.metadata not uploaded through Nextcloud

### ISSUE THREAD

**Issue by kromsam** [stevesoltys/backup#787]
I use Nextcloud as storage for my SeedVaultBackup. The whole backup is successfully uploaded, except two files: `.backup.icons` and `backup.metadata`. I looked into it and these are the errors I got in the log. They seem to be related.

**webdav**
`Exception Error while copying file to target location (copied: -1 byte, expected filesize: 15157 bytes)`
`Exception Error while copying file to target location (copied: -1 byte, expected filesize: 408631 bytes)`

**PHP**
`file_put_contents(/mnt/ncdata/<redacted>/files/.SeedVaultAndroidBackup/1717117045675/.backup.metadata): Failed to open stream: Permission denied at /var/www/html/lib/private/Files/Storage/Local.php#339`

`file_put_contents(/mnt/ncdata/<redacted>/files/.SeedVaultAndroidBackup/1717117045675/.backup.icons): Failed to open stream: Permission denied at /var/www/html/lib/private/Files/Storage/Local.php#339`

Is this a SeedVault issue or a Nextcloud issue?

**Comment by grote** [comment]
I'd bet on Nextcloud. Could you try the built-in WebDAV backend or DavX5 instead?

**Comment by grote** [comment]
Oh and if `backup.metadata` is missing you effectively don't have a backup.

**Comment by kromsam** [comment]
using the bèta webdav functionality seems to do it, thanks!
