### ISSUE TITLE
Ability to choose which (old) backup of an application to restore

### ISSUE THREAD

**Issue by tjanez** [stevesoltys/backup#802]
Now that one is able to restore an individual app after the profile is set up, it would be very convenient to also be able to restore a chosen (non-latest) backup version of the app.

For example, a user (accidentally) removes something from app's data and when the USB OTG is inserted, SeedVault automatically creates a backup of an app which has missing data.
It would be convenient to be able to select a previous backup to restore and recover the (accidentally) removed data.

**Comment by grote** [comment]
Seedvault 5.x creates snapshots and allows you to restore single apps from old snapshots already. Sounds like that would address your use-case.
