### ISSUE TITLE
Missing `Content-Length` header?

### ISSUE THREAD

**Issue by 0x1a8510f2** [stevesoltys/backup#806]
Related: https://github.com/owncloud/ocis/issues/10635

I've tried setting up WebDAV backup to OCIS and got the results as seen in the issue above. The OCIS devs say that this is caused by a lack of `Content-Length` HTTP header in the `PUT` request though I have not independently verified this.

I'm running OCIS behind Caddy but as far as I'm aware, this shouldn't have any impact.

**Comment by grote** [comment]
Seedvault used chunked transfer encoding and doesn't give the content length to the webserver. All server's we tested do support this. Curl for this works like this: `curl -X PUT -H 'Transfer-Encoding: chunked'`

**Comment by 0x1a8510f2** [comment]
I feel like this is going to spawn some back-and-forth with me as the messenger hah. I'll see what the OCIS devs say to that :D

**Comment by 0x1a8510f2** [comment]
Closing this for now since it seems like it is purely an OCIS issue. Thanks for your help!

**Comment by grote** [comment]
Note that a buffer size of around 15MB should work fine with Seedvault. It doesn't need to be as high as the entire backup.
