### ISSUE TITLE
changing WebDAV mount settings

### ISSUE THREAD

**Issue by sbinet** [stevesoltys/backup#813]
hi there,

I was playing with the "new" WebDAV mount feature of SeedVault with a local testing webdav server.
it worked.

now, I'd like to use a prod version of this WebDAV server, with different settings (domain, authentication, ...).
how would I do that ?
I don't seem to be able to modify the "WebDAV mount" settings from the "main" SeedVault backup menu, even with a long press.

is it possible to perform such a thing ?

**Comment by grote** [comment]
just tap "Backup location" and select WebDAV again and enter new data there.

btw. did you know we have [Discussions](https://github.com/seedvault-app/seedvault/discussions) for questions like these?

**Comment by sbinet** [comment]
Apologies for not using the discussions forum.
Maybe it's a seedvault 14-4.1 thing, but I didn't manage to go to a menu allowing to change the previous settings of the WebDAV mount.
Clicking on that button (re) launches the seedvault initialization
![Screenshot_20241211-201416_Trebuchet](https://github.com/user-attachments/assets/bd880204-d28a-405f-bf21-de759e59c136)
![Screenshot_20241211-201424_Trebuchet](https://github.com/user-attachments/assets/e294f5dd-49b1-4dfc-bb14-41dd1e975394)

**Comment by grote** [comment]
Oh, you are using WebDAV via DavX5 or the integrated "WebDAV Cloud (beta)"? If the former, you need to add a new mount in the DavX5 app. If the latter, you just tab "WebDAV Cloud (beta)" and then enter new credentials. Or are you saying that after tapping "WebDAV Cloud (beta)" it initializes without giving you the option to change? If so, I can't reproduce this here on the latest version.

**Comment by sbinet** [comment]
you're right: we were talking passed each other b/c of the WebDAV DavX5/Cloud confusion.
