### ISSUE TITLE
UX: Make it more evident that "Backup status" can be opened

### ISSUE THREAD

**Issue by lucasmz-dev** [stevesoltys/backup#827]
It isn't so clear that 'backup status' is an openable menu, it has a lot of important info such as what apps were backed up, app data backup size, etc. considering Seedvault can't always backup everything, this is important info and it should be a bit more clear that this is a menu that can be opened.

Contrary to the other options not-toggle options, this one doesn't imply in any way that it can be opened, just shows a date of the last backup. It could be confused with something that's just a static space for info

<details><summary>Screenshot</summary>
<p>

![image](https://github.com/user-attachments/assets/e30e91fd-e240-45aa-987b-3ce7b1e15c93)

</p>
</details>

**Comment by grote** [comment]
All of the items on the page can be opened and there are several others without toggle, but sure, some users may not realize that maybe.

**Comment by lucasmz-dev** [comment]
I'm still honestly thinking about this, I recall honestly thinking it was such a textbox, I feel like something's missing but can't tell what /shrug this was my suggestion until I realized:
It isn't as obvious but at the same time, regular Android settings work the same

**Comment by grote** [comment]
yeah the idea was to mimic Android's settings, so Seedvault blends right in and doesn't even appear as a separate app.
