### ISSUE TITLE
Backup fails after file backups

### ISSUE THREAD

**Issue by lucasmz-dev** [stevesoltys/backup#829]
I'm noticing a few backup failures sometimes when taking a backup when the file backup step is done; (if it's even done at all)

Logs: 
[seedvault-14-5.2-1735615863716.txt](https://github.com/user-attachments/files/18279118/seedvault-14-5.2-1735615863716.txt)

**Comment by grote** [comment]
from the log, this seems to be a duplicate of https://github.com/seedvault-app/seedvault/issues/828

and the fact that it happens to another person this may rule out flash drive issues. Maybe it is related to 5.1 or 5.2 changes.
